BEA SAGDP9_WV + BLS Employment dataset merging.

In [1]:
# Import libraries
import pandas as pd

print('Libraries imported successfully')

Libraries imported successfully

In [2]:
# Read in data
sagdp9wv_df = pd.read_csv('../../../workspace/nf-insights-project/data_clean/sagdp9wv_clean.csv', parse_dates=['Year'], low_memory=False)
blsemp_df = pd.read_csv('../../../workspace/nf-insights-project/data_clean/bls_employ_clean.csv', parse_dates=['Year'], low_memory=False)

print('CSVs read successfully!')

# Data check
print('Data check:')
print(sagdp9wv_df.head())
print(blsemp_df.head())

CSVs read successfully!
Data check:
        Year                           Industry  Real_GDP  Total_GDP  \
0 2006-01-01                       Construction    3667.8    70664.4
1 2006-01-01              Finance and Insurance    2748.4    70664.4
2 2006-01-01                         Government   12513.0    70664.4
3 2006-01-01  Health Care and Social Assistance    6346.2    70664.4
4 2006-01-01                        Information    1181.1    70664.4

   Industry_Share_Pct  Industry_GDP_Growth  Growth_Contribution  \
0                5.19                  NaN                  NaN
1                3.89                  NaN                  NaN
2               17.71                  NaN                  NaN
3                8.98                  NaN                  NaN
4                1.67                  NaN                  NaN

   Growth_Volatility  Industry_Rank
0              13.22              8
1               4.41             10
2               1.39              2
3               2.33              6
4               6.02             12
        Year                           Industry  Employment  YoY_Growth  \
0 2006-01-01                       Construction     39425.0         NaN
1 2006-01-01              Finance and Insurance     21250.0         NaN
2 2006-01-01                         Government    145608.3         NaN
3 2006-01-01  Health Care and Social Assistance    102408.3         NaN
4 2006-01-01                        Information     11508.3         NaN

   Total_Employment_Year  Industry_Share_Pct  Top3_Share_Pct  Industry_Rank
0               722683.2                5.46            54.0              7
1               722683.2                2.94            54.0             10
2               722683.2               20.15            54.0              1
3               722683.2               14.17            54.0              3
4               722683.2                1.59            54.0             11

In [3]:
# Data check
print('Data check:')
print(sagdp9wv_df.info())
print(blsemp_df.info())

Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 247 non-null    datetime64[ns]
 1   Industry             247 non-null    object
 2   Real_GDP             247 non-null    float64
 3   Total_GDP            247 non-null    float64
 4   Industry_Share_Pct   247 non-null    float64
 5   Industry_GDP_Growth  234 non-null    float64
 6   Growth_Contribution  234 non-null    float64
 7   Growth_Volatility    247 non-null    float64
 8   Industry_Rank        247 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 17.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   260 non-null    datetime64[ns]
 1   Industry               260 non-null    object
 2   Employment             260 non-null    float64
 3   YoY_Growth             247 non-null    float64
 4   Total_Employment_Year  260 non-null    float64
 5   Industry_Share_Pct     260 non-null    float64
 6   Top3_Share_Pct         260 non-null    float64
 7   Industry_Rank          260 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 16.4+ KB
None

In [4]:
# Check for matching industries
print(set(sagdp9wv_df['Industry']) - set(blsemp_df['Industry']))
print(set(blsemp_df['Industry']) - set(sagdp9wv_df['Industry']))

set()
set()

In [5]:
# Filter for years 2009-2024 before merging
sagdp9wv_df = sagdp9wv_df[(sagdp9wv_df['Year'].dt.year >= 2009) & 
                                (sagdp9wv_df['Year'].dt.year <= 2024)]
blsemp_df = blsemp_df[(blsemp_df['Year'].dt.year >= 2009) & 
                            (blsemp_df['Year'].dt.year <= 2024)]

print('Filtered successfully!')

# Data check
print('Data check:')
print(sagdp9wv_df.info())
print(blsemp_df.info())

Filtered successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 39 to 246
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 208 non-null    datetime64[ns]
 1   Industry             208 non-null    object
 2   Real_GDP             208 non-null    float64
 3   Total_GDP            208 non-null    float64
 4   Industry_Share_Pct   208 non-null    float64
 5   Industry_GDP_Growth  208 non-null    float64
 6   Growth_Contribution  208 non-null    float64
 7   Growth_Volatility    208 non-null    float64
 8   Industry_Rank        208 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 16.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 39 to 246
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   208 non-null    datetime64[ns]
 1   Industry               208 non-null    object
 2   Employment             208 non-null    float64
 3   YoY_Growth             208 non-null    float64
 4   Total_Employment_Year  208 non-null    float64
 5   Industry_Share_Pct     208 non-null    float64
 6   Top3_Share_Pct         208 non-null    float64
 7   Industry_Rank          208 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 14.6+ KB
None

In [6]:
# Merge dataframes
beagdp_blsemp = pd.merge(sagdp9wv_df, blsemp_df, how='inner', on=['Year', 'Industry'], suffixes=('_BEA', '_BLS'))

print('Merged successfully!')

# Reset index
beagdp_blsemp = beagdp_blsemp.reset_index(drop=True)

print('Index reset successfully!')  

# Data check
print('Data check:')
print('Data shape:', beagdp_blsemp.shape)
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Merged successfully!
Index reset successfully!
Data check:
Data shape: (208, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share_Pct_BEA  208 non-null    float64
 5   Industry_GDP_Growth     208 non-null    float64
 6   Growth_Contribution     208 non-null    float64
 7   Growth_Volatility       208 non-null    float64
 8   Industry_Rank_BEA       208 non-null    int64
 9   Employment              208 non-null    float64
 10  YoY_Growth              208 non-null    float64
 11  Total_Employment_Year   208 non-null    float64
 12  Industry_Share_Pct_BLS  208 non-null    float64
 13  Top3_Share_Pct          208 non-null    float64
 14  Industry_Rank_BLS       208 non-null    int64
dtypes: datetime64[ns](1), float64(11), int64(2), object(1)
memory usage: 24.5+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share_Pct_BEA,Industry_GDP_Growth,Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Employment,YoY_Growth,Total_Employment_Year,Industry_Share_Pct_BLS,Top3_Share_Pct,Industry_Rank_BLS
0,2009-01-01,Construction,3570.7,72467.2,4.93,-3.97,-0.20,13.22,8,34075.0,-12.42,710933.3,4.79,55.6,7
1,2009-01-01,Finance and Insurance,2946.8,72467.2,4.07,9.98,0.37,4.41,9,19775.0,-4.12,710933.3,2.78,55.6,10
2,2009-01-01,Government,12834.8,72467.2,17.71,1.95,0.34,1.39,1,150025.0,1.71,710933.3,21.10,55.6,1
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,9.43,3.15,0.29,2.33,6,109241.7,2.42,710933.3,15.37,55.6,3
4,2009-01-01,Information,1263.6,72467.2,1.74,-4.86,-0.09,6.02,12,10433.3,-6.50,710933.3,1.47,55.6,11

In [7]:
# Round for readability (2 decimals)
pct_cols = [
    'Industry_Share_Pct_BEA',
    'Industry_Share_Pct_BLS',
    'Industry_GDP_Growth',
    'Growth_Contribution',
    'YoY_Growth',
    'Top3_Share_Pct'
]

beagdp_blsemp[pct_cols] = beagdp_blsemp[pct_cols].round(2)

print('Rounded to 2 decimals successfully!')

# Round for readability (1 decimal)
conc_cols = ['Growth_Volatility']

beagdp_blsemp[conc_cols] = beagdp_blsemp[conc_cols].round(1)

print('Rounded to 1 decimal successfully!')

# Convert to int
beagdp_blsemp['Employment'] = beagdp_blsemp['Employment'].astype(int)
beagdp_blsemp['Total_Employment_Year'] = beagdp_blsemp['Total_Employment_Year'].astype(int)

print('Converted to int successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Rounded to 2 decimals successfully!
Rounded to 1 decimal successfully!
Converted to int successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share_Pct_BEA  208 non-null    float64
 5   Industry_GDP_Growth     208 non-null    float64
 6   Growth_Contribution     208 non-null    float64
 7   Growth_Volatility       208 non-null    float64
 8   Industry_Rank_BEA       208 non-null    int64
 9   Employment              208 non-null    int64
 10  YoY_Growth              208 non-null    float64
 11  Total_Employment_Year   208 non-null    int64
 12  Industry_Share_Pct_BLS  208 non-null    float64
 13  Top3_Share_Pct          208 non-null    float64
 14  Industry_Rank_BLS       208 non-null    int64
dtypes: datetime64[ns](1), float64(9), int64(4), object(1)
memory usage: 24.5+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share_Pct_BEA,Industry_GDP_Growth,Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Employment,YoY_Growth,Total_Employment_Year,Industry_Share_Pct_BLS,Top3_Share_Pct,Industry_Rank_BLS
0,2009-01-01,Construction,3570.7,72467.2,4.93,-3.97,-0.20,13.2,8,34075,-12.42,710933,4.79,55.6,7
1,2009-01-01,Finance and Insurance,2946.8,72467.2,4.07,9.98,0.37,4.4,9,19775,-4.12,710933,2.78,55.6,10
2,2009-01-01,Government,12834.8,72467.2,17.71,1.95,0.34,1.4,1,150025,1.71,710933,21.10,55.6,1
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,9.43,3.15,0.29,2.3,6,109241,2.42,710933,15.37,55.6,3
4,2009-01-01,Information,1263.6,72467.2,1.74,-4.86,-0.09,6.0,12,10433,-6.50,710933,1.47,55.6,11

In [8]:
# Calculate GDP per worker (productivity)
beagdp_blsemp['GDP_per_Worker'] = (beagdp_blsemp['Real_GDP'] * 1_000_000) / beagdp_blsemp['Employment']

print('GDP per worker calculated successfully!')

# Round for readability
beagdp_blsemp['GDP_per_Worker'] = beagdp_blsemp['GDP_per_Worker'].round(2)

print('Values rounded successfully!')

# Convert to int
beagdp_blsemp['GDP_per_Worker'] = beagdp_blsemp['GDP_per_Worker'].astype(int)

print('Converted to int successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

GDP per worker calculated successfully!
Values rounded successfully!
Converted to int successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share_Pct_BEA  208 non-null    float64
 5   Industry_GDP_Growth     208 non-null    float64
 6   Growth_Contribution     208 non-null    float64
 7   Growth_Volatility       208 non-null    float64
 8   Industry_Rank_BEA       208 non-null    int64
 9   Employment              208 non-null    int64
 10  YoY_Growth              208 non-null    float64
 11  Total_Employment_Year   208 non-null    int64
 12  Industry_Share_Pct_BLS  208 non-null    float64
 13  Top3_Share_Pct          208 non-null    float64
 14  Industry_Rank_BLS       208 non-null    int64
 15  GDP_per_Worker          208 non-null    int64
dtypes: datetime64[ns](1), float64(9), int64(5), object(1)
memory usage: 26.1+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share_Pct_BEA,Industry_GDP_Growth,Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Employment,YoY_Growth,Total_Employment_Year,Industry_Share_Pct_BLS,Top3_Share_Pct,Industry_Rank_BLS,GDP_per_Worker
0,2009-01-01,Construction,3570.7,72467.2,4.93,-3.97,-0.20,13.2,8,34075,-12.42,710933,4.79,55.6,7,104789
1,2009-01-01,Finance and Insurance,2946.8,72467.2,4.07,9.98,0.37,4.4,9,19775,-4.12,710933,2.78,55.6,10,149016
2,2009-01-01,Government,12834.8,72467.2,17.71,1.95,0.34,1.4,1,150025,1.71,710933,21.10,55.6,1,85551
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,9.43,3.15,0.29,2.3,6,109241,2.42,710933,15.37,55.6,3,62582
4,2009-01-01,Information,1263.6,72467.2,1.74,-4.86,-0.09,6.0,12,10433,-6.50,710933,1.47,55.6,11,121115

In [9]:
# Calculate output vs employment gap
beagdp_blsemp['Output_Gap'] = beagdp_blsemp['Industry_Share_Pct_BEA'] - beagdp_blsemp['Industry_Share_Pct_BLS']

print('Output vs employment gap calculated successfully!')

# Round for readability
beagdp_blsemp['Output_Gap'] = beagdp_blsemp['Output_Gap'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Output vs employment gap calculated successfully!
Values rounded successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share_Pct_BEA  208 non-null    float64
 5   Industry_GDP_Growth     208 non-null    float64
 6   Growth_Contribution     208 non-null    float64
 7   Growth_Volatility       208 non-null    float64
 8   Industry_Rank_BEA       208 non-null    int64
 9   Employment              208 non-null    int64
 10  YoY_Growth              208 non-null    float64
 11  Total_Employment_Year   208 non-null    int64
 12  Industry_Share_Pct_BLS  208 non-null    float64
 13  Top3_Share_Pct          208 non-null    float64
 14  Industry_Rank_BLS       208 non-null    int64
 15  GDP_per_Worker          208 non-null    int64
 16  Output_Gap              208 non-null    float64
dtypes: datetime64[ns](1), float64(10), int64(5), object(1)
memory usage: 27.8+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share_Pct_BEA,Industry_GDP_Growth,Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Employment,YoY_Growth,Total_Employment_Year,Industry_Share_Pct_BLS,Top3_Share_Pct,Industry_Rank_BLS,GDP_per_Worker,Output_Gap
0,2009-01-01,Construction,3570.7,72467.2,4.93,-3.97,-0.20,13.2,8,34075,-12.42,710933,4.79,55.6,7,104789,0.14
1,2009-01-01,Finance and Insurance,2946.8,72467.2,4.07,9.98,0.37,4.4,9,19775,-4.12,710933,2.78,55.6,10,149016,1.29
2,2009-01-01,Government,12834.8,72467.2,17.71,1.95,0.34,1.4,1,150025,1.71,710933,21.10,55.6,1,85551,-3.39
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,9.43,3.15,0.29,2.3,6,109241,2.42,710933,15.37,55.6,3,62582,-5.94
4,2009-01-01,Information,1263.6,72467.2,1.74,-4.86,-0.09,6.0,12,10433,-6.50,710933,1.47,55.6,11,121115,0.27

In [10]:
# Calculate growth contribution vs employment growth to see misalignment
beagdp_blsemp['Employment_vs_Growth_Alignment'] = beagdp_blsemp['YoY_Growth'] * beagdp_blsemp['Growth_Contribution']

print('Growth contribution vs employment growth misalignment calculated successfully!')

# Round for readability
beagdp_blsemp['Employment_vs_Growth_Alignment'] = beagdp_blsemp['Employment_vs_Growth_Alignment'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Growth contribution vs employment growth misalignment calculated successfully!
Values rounded successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            208 non-null    datetime64[ns]
 1   Industry                        208 non-null    object
 2   Real_GDP                        208 non-null    float64
 3   Total_GDP                       208 non-null    float64
 4   Industry_Share_Pct_BEA          208 non-null    float64
 5   Industry_GDP_Growth             208 non-null    float64
 6   Growth_Contribution             208 non-null    float64
 7   Growth_Volatility               208 non-null    float64
 8   Industry_Rank_BEA               208 non-null    int64
 9   Employment                      208 non-null    int64
 10  YoY_Growth                      208 non-null    float64
 11  Total_Employment_Year           208 non-null    int64
 12  Industry_Share_Pct_BLS          208 non-null    float64
 13  Top3_Share_Pct                  208 non-null    float64
 14  Industry_Rank_BLS               208 non-null    int64
 15  GDP_per_Worker                  208 non-null    int64
 16  Output_Gap                      208 non-null    float64
 17  Employment_vs_Growth_Alignment  208 non-null    float64
dtypes: datetime64[ns](1), float64(11), int64(5), object(1)
memory usage: 29.4+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share_Pct_BEA,Industry_GDP_Growth,Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Employment,YoY_Growth,Total_Employment_Year,Industry_Share_Pct_BLS,Top3_Share_Pct,Industry_Rank_BLS,GDP_per_Worker,Output_Gap,Employment_vs_Growth_Alignment
0,2009-01-01,Construction,3570.7,72467.2,4.93,-3.97,-0.20,13.2,8,34075,-12.42,710933,4.79,55.6,7,104789,0.14,2.48
1,2009-01-01,Finance and Insurance,2946.8,72467.2,4.07,9.98,0.37,4.4,9,19775,-4.12,710933,2.78,55.6,10,149016,1.29,-1.52
2,2009-01-01,Government,12834.8,72467.2,17.71,1.95,0.34,1.4,1,150025,1.71,710933,21.10,55.6,1,85551,-3.39,0.58
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,9.43,3.15,0.29,2.3,6,109241,2.42,710933,15.37,55.6,3,62582,-5.94,0.70
4,2009-01-01,Information,1263.6,72467.2,1.74,-4.86,-0.09,6.0,12,10433,-6.50,710933,1.47,55.6,11,121115,0.27,0.58

In [11]:
# Drop unnecessary columns for final dataset for dashboard
beagdp_blsemp_clean = beagdp_blsemp.drop(columns=['Total_GDP', 'Total_Employment_Year', 'Output_Gap'])

print('Unnecessary columns dropped successfully!')

# Rename columns for clarity
beagdp_blsemp_clean = beagdp_blsemp_clean.rename(columns={
    'Real_GDP': 'Industry_GDP',
    'Industry_Share_Pct_BEA': 'Industry_GDP_Share',
    'Growth_Contribution': 'Industry_Growth_Contribution',
    'Employment': 'Industry_Employment',
    'YoY_Growth': 'Employment_Growth',
    'Industry_Share_Pct_BLS': 'Industry_Employment_Share',
    'Top3_Share_Pct': 'Top3_Employment_Share'
})

print('Columns renamed successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp_clean.info())

Unnecessary columns dropped successfully!
Columns renamed successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            208 non-null    datetime64[ns]
 1   Industry                        208 non-null    object
 2   Industry_GDP                    208 non-null    float64
 3   Industry_GDP_Share              208 non-null    float64
 4   Industry_GDP_Growth             208 non-null    float64
 5   Industry_Growth_Contribution    208 non-null    float64
 6   Growth_Volatility               208 non-null    float64
 7   Industry_Rank_BEA               208 non-null    int64
 8   Industry_Employment             208 non-null    int64
 9   Employment_Growth               208 non-null    float64
 10  Industry_Employment_Share       208 non-null    float64
 11  Top3_Employment_Share           208 non-null    float64
 12  Industry_Rank_BLS               208 non-null    int64
 13  GDP_per_Worker                  208 non-null    int64
 14  Employment_vs_Growth_Alignment  208 non-null    float64
dtypes: datetime64[ns](1), float64(9), int64(4), object(1)
memory usage: 24.5+ KB
None

In [12]:
# Convert Industry_GDP values to millions of dollars for readability
beagdp_blsemp_clean['Industry_GDP'] = beagdp_blsemp_clean['Industry_GDP'] / 1_000

print('Industry_GDP converted to millions successfully!')

# Round for readability
beagdp_blsemp_clean['Industry_GDP_Share'] = beagdp_blsemp_clean['Industry_GDP_Share'].round(1)
beagdp_blsemp_clean['Industry_GDP_Growth'] = beagdp_blsemp_clean['Industry_GDP_Growth'].round(1)
beagdp_blsemp_clean['Employment_Growth'] = beagdp_blsemp_clean['Employment_Growth'].round(1)
beagdp_blsemp_clean['Industry_GDP'] = beagdp_blsemp_clean['Industry_GDP'].round(2)

print('Values rounded successfully!')

# Reset index
beagdp_blsemp_clean = beagdp_blsemp_clean.reset_index(drop=True)

print('Index reset successfully!')

# Data check
print('Data check:')
beagdp_blsemp_clean.head()

Industry_GDP converted to millions successfully!
Values rounded successfully!
Index reset successfully!
Data check:

,Year,Industry,Industry_GDP,Industry_GDP_Share,Industry_GDP_Growth,Industry_Growth_Contribution,Growth_Volatility,Industry_Rank_BEA,Industry_Employment,Employment_Growth,Industry_Employment_Share,Top3_Employment_Share,Industry_Rank_BLS,GDP_per_Worker,Employment_vs_Growth_Alignment
0,2009-01-01,Construction,3.57,4.9,-4.0,-0.20,13.2,8,34075,-12.4,4.79,55.6,7,104789,2.48
1,2009-01-01,Finance and Insurance,2.95,4.1,10.0,0.37,4.4,9,19775,-4.1,2.78,55.6,10,149016,-1.52
2,2009-01-01,Government,12.83,17.7,2.0,0.34,1.4,1,150025,1.7,21.10,55.6,1,85551,0.58
3,2009-01-01,Health Care and Social Assistance,6.84,9.4,3.2,0.29,2.3,6,109241,2.4,15.37,55.6,3,62582,0.70
4,2009-01-01,Information,1.26,1.7,-4.9,-0.09,6.0,12,10433,-6.5,1.47,55.6,11,121115,0.58

In [13]:
# Save to CSV
beagdp_blsemp_clean.to_csv('../../../workspace/nf-insights-project/data_clean/beagdp_blsemp_merge_clean.csv', index=False)

print('CSV saved successfully!')

CSV saved successfully!