BEA SAGDP9 WV data cleaning and exploration.

In [1]:
# Import libraries
import pandas as pd
import re

print('Libraries imported successfully!')

Libraries imported successfully!

In [2]:
# Read in data
sagdp9wv_df = pd.read_csv('../../../workspace/nf-insights-project/data_raw/BEA GDP Data/SAGDP9_WV_1997_2024.csv', low_memory=False)

print('CSV read successfully!')

sagdp9wv_df.head()

CSV read successfully!

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"""54000""",West Virginia,5.0,SAGDP9,1.0,...,All industry total,Millions of chained 2017 dollars,60364.6,61725.7,...,74261.4,73513.3,75172.4,77406.5,77162.2,74729.6,76230.8,77549.1,80364.9,82716.5
1,"""54000""",West Virginia,5.0,SAGDP9,2.0,...,Private industries,Millions of chained 2017 dollars,49292.6,50584.3,...,62201.0,61686.8,63338.1,65574.3,65117.8,62549.6,63864.3,65258.7,68096.5,70377.0
2,"""54000""",West Virginia,5.0,SAGDP9,3.0,11,"Agriculture, forestry, fishing and hunting",Millions of chained 2017 dollars,248.5,249.8,...,331.9,341.1,389.1,366.2,368.2,291.9,318.0,455.4,347.9,443.3
3,"""54000""",West Virginia,5.0,SAGDP9,4.0,111-112,Farms,Millions of chained 2017 dollars,102.6,113.7,...,187.6,195.5,246.7,228.0,231.6,165.7,194.4,320.3,226.8,311.4
4,"""54000""",West Virginia,5.0,SAGDP9,5.0,113-115,"Forestry, fishing, and related activities",Millions of chained 2017 dollars,158.6,146.7,...,143.4,144.7,142.4,138.1,136.6,124.4,121.4,117.9,114.6,118.7

In [3]:
# Data check
print('Data check:')
print('Data shape:', sagdp9wv_df.shape)
print(sagdp9wv_df.info())
sagdp9wv_df.columns

Data check:
Data shape: (96, 36)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoFIPS                 96 non-null     object
 1   GeoName                 92 non-null     object
 2   Region                  92 non-null     float64
 3   TableName               92 non-null     object
 4   LineCode                92 non-null     float64
 5   IndustryClassification  92 non-null     object
 6   Description             92 non-null     object
 7   Unit                    92 non-null     object
 8   1997                    92 non-null     float64
 9   1998                    92 non-null     float64
 10  1999                    92 non-null     float64
 11  2000                    92 non-null     float64
 12  2001                    92 non-null     float64
 13  2002                    92 non-null     float64
 14  2003                    92 non-null     float64
 15  2004                    92 non-null     float64
 16  2005                    92 non-null     float64
 17  2006                    92 non-null     float64
 18  2007                    92 non-null     float64
 19  2008                    92 non-null     float64
 20  2009                    92 non-null     float64
 21  2010                    92 non-null     float64
 22  2011                    92 non-null     float64
 23  2012                    92 non-null     float64
 24  2013                    92 non-null     float64
 25  2014                    92 non-null     float64
 26  2015                    92 non-null     float64
 27  2016                    92 non-null     float64
 28  2017                    92 non-null     float64
 29  2018                    92 non-null     float64
 30  2019                    92 non-null     float64
 31  2020                    92 non-null     float64
 32  2021                    92 non-null     float64
 33  2022                    92 non-null     float64
 34  2023                    92 non-null     float64
 35  2024                    92 non-null     float64
dtypes: float64(30), object(6)
memory usage: 27.1+ KB
None

Index(['GeoFIPS', 'GeoName', 'Region', 'TableName', 'LineCode',
       'IndustryClassification', 'Description', 'Unit', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='object')

In [4]:
# Drop unnecessary columns
years = [str(y) for y in range(2006, 2025)]

sagdp9wv_df = sagdp9wv_df[['GeoName', 'LineCode', 'IndustryClassification', 'Description', 'Unit'] + years]

print('Unnecessary columns dropped successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_df.shape)
sagdp9wv_df.info()

Unnecessary columns dropped successfully!
Data check:
Data shape: (96, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoName                 92 non-null     object
 1   LineCode                92 non-null     float64
 2   IndustryClassification  92 non-null     object
 3   Description             92 non-null     object
 4   Unit                    92 non-null     object
 5   2006                    92 non-null     float64
 6   2007                    92 non-null     float64
 7   2008                    92 non-null     float64
 8   2009                    92 non-null     float64
 9   2010                    92 non-null     float64
 10  2011                    92 non-null     float64
 11  2012                    92 non-null     float64
 12  2013                    92 non-null     float64
 13  2014                    92 non-null     float64
 14  2015                    92 non-null     float64
 15  2016                    92 non-null     float64
 16  2017                    92 non-null     float64
 17  2018                    92 non-null     float64
 18  2019                    92 non-null     float64
 19  2020                    92 non-null     float64
 20  2021                    92 non-null     float64
 21  2022                    92 non-null     float64
 22  2023                    92 non-null     float64
 23  2024                    92 non-null     float64
dtypes: float64(20), object(4)
memory usage: 18.1+ KB

In [5]:
# Drop completely empty rows
sagdp9wv_df = sagdp9wv_df.dropna(how='all', axis=0)

print('Completely empty rows dropped successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_df.shape)

Completely empty rows dropped successfully!
Data check:
Data shape: (92, 24)

In [6]:
# Melt df from wide -> long
# Columns that identify each row
id_vars = ['GeoName', 'LineCode', 'IndustryClassification', 'Description', 'Unit']

# Columns to turn into rows
value_vars = [str(y) for y in range(2006, 2025)]

sagdp9wv_long = pd.melt(
    sagdp9wv_df,
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Year',
    value_name='GDPReal'
)

print('Data melted successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_long.shape)
print(sagdp9wv_long.info())

Data melted successfully!
Data check:
Data shape: (1748, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1748 entries, 0 to 1747
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoName                 1748 non-null   object
 1   LineCode                1748 non-null   float64
 2   IndustryClassification  1748 non-null   object
 3   Description             1748 non-null   object
 4   Unit                    1748 non-null   object
 5   Year                    1748 non-null   object
 6   GDPReal                 1748 non-null   float64
dtypes: float64(2), object(5)
memory usage: 95.7+ KB
None

In [7]:
# Convert LineCode and Year from float64 to Int64
sagdp9wv_long['LineCode'] = sagdp9wv_long['LineCode'].astype('Int64')

# Convert Year from object to int
sagdp9wv_long['Year'] = sagdp9wv_long['Year'].astype('Int64')

print('Data types converted successfully!')

# Data check
print('Data check:')
print(sagdp9wv_long.info())
sagdp9wv_long.head()

Data types converted successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1748 entries, 0 to 1747
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoName                 1748 non-null   object
 1   LineCode                1748 non-null   Int64
 2   IndustryClassification  1748 non-null   object
 3   Description             1748 non-null   object
 4   Unit                    1748 non-null   object
 5   Year                    1748 non-null   Int64
 6   GDPReal                 1748 non-null   float64
dtypes: Int64(2), float64(1), object(4)
memory usage: 99.1+ KB
None

,GeoName,LineCode,IndustryClassification,Description,Unit,Year,GDPReal
0,West Virginia,1,...,All industry total,Millions of chained 2017 dollars,2006,68900.0
1,West Virginia,2,...,Private industries,Millions of chained 2017 dollars,2006,56480.0
2,West Virginia,3,11,"Agriculture, forestry, fishing and hunting",Millions of chained 2017 dollars,2006,338.4
3,West Virginia,4,111-112,Farms,Millions of chained 2017 dollars,2006,150.0
4,West Virginia,5,113-115,"Forestry, fishing, and related activities",Millions of chained 2017 dollars,2006,200.6

In [8]:
# Select the columns we need to map industries
cols_to_check = ['LineCode', 'IndustryClassification', 'Description']

print('Columns selected successfully!')

# Drop duplicates so we only see each industry once
bea_industries = sagdp9wv_long[cols_to_check].drop_duplicates()

print('Duplicates dropped successfully!')

# Sort by LineCode to see top-level sectors first
bea_industries = bea_industries.sort_values('LineCode')

print('Data sorted successfully!')

# Show the rows
print(bea_industries.head(92).to_markdown(index=False))

Columns selected successfully!
Duplicates dropped successfully!
Data sorted successfully!
|   LineCode | IndustryClassification   | Description                                                                             |
|-----------:|:-------------------------|:----------------------------------------------------------------------------------------|
|          1 | ...                      | All industry total                                                                      |
|          2 | ...                      | Private industries                                                                      |
|          3 | 11                       | Agriculture, forestry, fishing and hunting                                              |
|          4 | 111-112                  | Farms                                                                                   |
|          5 | 113-115                  | Forestry, fishing, and related activities                                               |
|          6 | 21                       | Mining, quarrying, and oil and gas extraction                                           |
|          7 | 211                      | Oil and gas extraction                                                                  |
|          8 | 212                      | Mining (except oil and gas)                                                             |
|          9 | 213                      | Support activities for mining                                                           |
|         10 | 22                       | Utilities                                                                               |
|         11 | 23                       | Construction                                                                            |
|         12 | 31-33                    | Manufacturing                                                                           |
|         13 | 321,327-339              | Durable goods manufacturing                                                             |
|         14 | 321                      | Wood product manufacturing                                                              |
|         15 | 327                      | Nonmetallic mineral product manufacturing                                               |
|         16 | 331                      | Primary metal manufacturing                                                             |
|         17 | 332                      | Fabricated metal product manufacturing                                                  |
|         18 | 333                      | Machinery manufacturing                                                                 |
|         19 | 334                      | Computer and electronic product manufacturing                                           |
|         20 | 335                      | Electrical equipment, appliance, and component manufacturing                            |
|         21 | 3361-3363                | Motor vehicles, bodies and trailers, and parts manufacturing                            |
|         22 | 3364-3466,3369           | Other transportation equipment manufacturing                                            |
|         23 | 337                      | Furniture and related product manufacturing                                             |
|         24 | 339                      | Miscellaneous manufacturing                                                             |
|         25 | 311-316,322-326          | Nondurable goods manufacturing                                                          |
|         26 | 311-312                  | Food and beverage and tobacco product manufacturing                                     |
|         27 | 313-314                  | Textile mills and textile product mills                                                 |
|         28 | 315-316                  | Apparel, leather, and allied product manufacturing                                      |
|         29 | 322                      | Paper manufacturing                                                                     |
|         30 | 323                      | Printing and related support activities                                                 |
|         31 | 324                      | Petroleum and coal products manufacturing                                               |
|         32 | 325                      | Chemical manufacturing                                                                  |
|         33 | 326                      | Plastics and rubber products manufacturing                                              |
|         34 | 42                       | Wholesale trade                                                                         |
|         35 | 44-45                    | Retail trade                                                                            |
|         36 | 48-49                    | Transportation and warehousing                                                          |
|         37 | 481                      | Air transportation                                                                      |
|         38 | 482                      | Rail transportation                                                                     |
|         39 | 483                      | Water transportation                                                                    |
|         40 | 484                      | Truck transportation                                                                    |
|         41 | 485                      | Transit and ground passenger transportation                                             |
|         42 | 486                      | Pipeline transportation                                                                 |
|         43 | 487-488,492              | Other transportation and support activities                                             |
|         44 | 493                      | Warehousing and storage                                                                 |
|         45 | 51                       | Information                                                                             |
|         46 | 511                      | Publishing industries (except Internet)                                                 |
|         47 | 512                      | Motion picture and sound recording industries                                           |
|         48 | 515,517                  | Broadcasting (except Internet) and telecommunications                                   |
|         49 | 518-519                  | Data processing, hosting, and other information services                                |
|         50 | 52,53                    | Finance, insurance, real estate, rental, and leasing                                    |
|         51 | 52                       | Finance and insurance                                                                   |
|         52 | 521-522                  | Monetary Authorities- central bank, credit intermediation, and related services         |
|         53 | 523                      | Securities, commodity contracts, and other financial investments and related activities |
|         54 | 524                      | Insurance carriers and related activities                                               |
|         55 | 525                      | Funds, trusts, and other financial vehicles                                             |
|         56 | 53                       | Real estate and rental and leasing                                                      |
|         57 | 531                      | Real estate                                                                             |
|         58 | 532-533                  | Rental and leasing services and lessors of nonfinancial intangible assets               |
|         59 | 54,55,56                 | Professional and business services                                                      |
|         60 | 54                       | Professional, scientific, and technical services                                        |
|         61 | 5411                     | Legal services                                                                          |
|         62 | 5415                     | Computer systems design and related services                                            |
|         63 | 5412-5414,5416-5419      | Miscellaneous professional, scientific, and technical services                          |
|         64 | 55                       | Management of companies and enterprises                                                 |
|         65 | 56                       | Administrative and support and waste management and remediation services                |
|         66 | 561                      | Administrative and support services                                                     |
|         67 | 562                      | Waste management and remediation services                                               |
|         68 | 61,62                    | Educational services, health care, and social assistance                                |
|         69 | 61                       | Educational services                                                                    |
|         70 | 62                       | Health care and social assistance                                                       |
|         71 | 621                      | Ambulatory health care services                                                         |
|         72 | 622                      | Hospitals                                                                               |
|         73 | 623                      | Nursing and residential care facilities                                                 |
|         74 | 624                      | Social assistance                                                                       |
|         75 | 71,72                    | Arts, entertainment, recreation, accommodation, and food services                       |
|         76 | 71                       | Arts, entertainment, and recreation                                                     |
|         77 | 711-712                  | Performing arts, spectator sports, museums, and related activities                      |
|         78 | 713                      | Amusement, gambling, and recreation industries                                          |
|         79 | 72                       | Accommodation and food services                                                         |
|         80 | 721                      | Accommodation                                                                           |
|         81 | 722                      | Food services and drinking places                                                       |
|         82 | 81                       | Other services (except government and government enterprises)                           |
|         83 | 92                       | Government and government enterprises                                                   |
|         84 | ...                      | Federal civilian                                                                        |
|         85 | ...                      | Military                                                                                |
|         86 | ...                      | State and local                                                                         |
|         87 | 11,21                    | Natural resources and mining                                                            |
|         88 | 42,44-45                 | Trade                                                                                   |
|         89 | 22,48-49                 | Transportation and utilities                                                            |
|         90 | 31-33,51                 | Manufacturing and information                                                           |
|         91 | ...                      | Private goods-producing industries 2/                                                   |
|         92 | ...                      | Private services-providing industries 3/                                                |

In [9]:
# Strip whitespace from all text columns
text_cols = sagdp9wv_long.select_dtypes(include='object').columns

for col in text_cols:
    sagdp9wv_long[col] = sagdp9wv_long[col].str.strip()

print('Whitespace stripped successfully!')

Whitespace stripped successfully!

In [10]:
# Map BEA industries to top-level industries
bea_mapping = {
    # Keep top-level total
    'All industry total': 'Total Nonfarm',

    # Agriculture / Mining / Natural resources
    'Farms': 'Mining and Logging',
    'Forestry, fishing, and related activities': 'Mining and Logging',
    'Oil and gas extraction': 'Mining and Logging',
    'Mining (except oil and gas)': 'Mining and Logging',
    'Support activities for mining': 'Mining and Logging',

    # Utilities
    'Utilities': 'Trade, Transportation, and Utilities',

    # Construction
    'Construction': 'Construction',

    # Manufacturing
    'Manufacturing': 'Manufacturing',

    # Trade / Transportation / Utilities
    'Wholesale trade': 'Trade, Transportation, and Utilities',
    'Retail trade': 'Trade, Transportation, and Utilities',
    'Transportation and warehousing': 'Trade, Transportation, and Utilities',

    # Information
    'Information': 'Information',

    # Finance, Insurance, Real Estate, Rental and Leasing
    'Finance and insurance': 'Finance and Insurance',
    'Real estate': 'Real Estate and Rental and Leasing',
    'Rental and leasing services and lessors of nonfinancial intangible assets': 'Real Estate and Rental and Leasing',

    # Professional and Business Services
    'Professional, scientific, and technical services': 'Professional and Business Services',
    'Management of companies and enterprises': 'Professional and Business Services',
    'Administrative and support and waste management and remediation services': 'Professional and Business Services',

    # Education / Health
    'Educational services': 'Private Educational Services',
    'Health care and social assistance': 'Health Care and Social Assistance',

    # Arts / Leisure / Hospitality
    'Arts, entertainment, and recreation': 'Leisure and Hospitality',
    'Accommodation and food services': 'Leisure and Hospitality',

    # Other Services
    'Other services (except government and government enterprises)': 'Other Services',

    # Government
    'Government and government enterprises': 'Government',
}

# Create a new column for industries using the mapping
sagdp9wv_long['Industry'] = sagdp9wv_long['Description'].map(bea_mapping)

print('BEA industries mapped successfully!')

# Check for any unmapped industries
unmapped = sagdp9wv_long[sagdp9wv_long['Industry'].isna()]['Description'].unique()
print('Unmapped BEA industries (if any):', unmapped)

# Drop rows that are parent lines or aggregates that are not needed
sagdp9wv_long = sagdp9wv_long.dropna(subset=['Industry'])

print('BEA parent lines or aggregate industries dropped successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_long.shape)
sagdp9wv_long.head(20)

BEA industries mapped successfully!
Unmapped BEA industries (if any): ['Private industries' 'Agriculture, forestry, fishing and hunting'
 'Mining, quarrying, and oil and gas extraction'
 'Durable goods manufacturing' 'Wood product manufacturing'
 'Nonmetallic mineral product manufacturing' 'Primary metal manufacturing'
 'Fabricated metal product manufacturing' 'Machinery manufacturing'
 'Computer and electronic product manufacturing'
 'Electrical equipment, appliance, and component manufacturing'
 'Motor vehicles, bodies and trailers, and parts manufacturing'
 'Other transportation equipment manufacturing'
 'Furniture and related product manufacturing'
 'Miscellaneous manufacturing' 'Nondurable goods manufacturing'
 'Food and beverage and tobacco product manufacturing'
 'Textile mills and textile product mills'
 'Apparel, leather, and allied product manufacturing'
 'Paper manufacturing' 'Printing and related support activities'
 'Petroleum and coal products manufacturing' 'Chemical manufacturing'
 'Plastics and rubber products manufacturing' 'Air transportation'
 'Rail transportation' 'Water transportation' 'Truck transportation'
 'Transit and ground passenger transportation' 'Pipeline transportation'
 'Other transportation and support activities' 'Warehousing and storage'
 'Publishing industries (except Internet)'
 'Motion picture and sound recording industries'
 'Broadcasting (except Internet) and telecommunications'
 'Data processing, hosting, and other information services'
 'Finance, insurance, real estate, rental, and leasing'
 'Monetary Authorities- central bank, credit intermediation, and related services'
 'Securities, commodity contracts, and other financial investments and related activities'
 'Insurance carriers and related activities'
 'Funds, trusts, and other financial vehicles'
 'Real estate and rental and leasing' 'Professional and business services'
 'Legal services' 'Computer systems design and related services'
 'Miscellaneous professional, scientific, and technical services'
 'Administrative and support services'
 'Waste management and remediation services'
 'Educational services, health care, and social assistance'
 'Ambulatory health care services' 'Hospitals'
 'Nursing and residential care facilities' 'Social assistance'
 'Arts, entertainment, recreation, accommodation, and food services'
 'Performing arts, spectator sports, museums, and related activities'
 'Amusement, gambling, and recreation industries' 'Accommodation'
 'Food services and drinking places' 'Federal civilian' 'Military'
 'State and local' 'Natural resources and mining' 'Trade'
 'Transportation and utilities' 'Manufacturing and information'
 'Private goods-producing industries 2/'
 'Private services-providing industries 3/']
BEA parent lines or aggregate industries dropped successfully!
Data check:
Data shape: (475, 8)

,GeoName,LineCode,IndustryClassification,Description,Unit,Year,GDPReal,Industry
0,West Virginia,1,...,All industry total,Millions of chained 2017 dollars,2006,68900.0,Total Nonfarm
3,West Virginia,4,111-112,Farms,Millions of chained 2017 dollars,2006,150.0,Mining and Logging
4,West Virginia,5,113-115,"Forestry, fishing, and related activities",Millions of chained 2017 dollars,2006,200.6,Mining and Logging
6,West Virginia,7,211,Oil and gas extraction,Millions of chained 2017 dollars,2006,292.5,Mining and Logging
7,West Virginia,8,212,Mining (except oil and gas),Millions of chained 2017 dollars,2006,5911.6,Mining and Logging
8,West Virginia,9,213,Support activities for mining,Millions of chained 2017 dollars,2006,701.1,Mining and Logging
9,West Virginia,10,22,Utilities,Millions of chained 2017 dollars,2006,1778.3,"Trade, Transportation, and Utilities"
10,West Virginia,11,23,Construction,Millions of chained 2017 dollars,2006,3667.8,Construction
11,West Virginia,12,31-33,Manufacturing,Millions of chained 2017 dollars,2006,7616.3,Manufacturing
33,West Virginia,34,42,Wholesale trade,Millions of chained 2017 dollars,2006,3616.2,"Trade, Transportation, and Utilities"
34,West Virginia,35,44-45,Retail trade,Millions of chained 2017 dollars,2006,4964.1,"Trade, Transportation, and Utilities"
35,West Virginia,36,48-49,Transportation and warehousing,Millions of chained 2017 dollars,2006,2400.1,"Trade, Transportation, and Utilities"
44,West Virginia,45,51,Information,Millions of chained 2017 dollars,2006,1181.1,Information
50,West Virginia,51,52,Finance and insurance,Millions of chained 2017 dollars,2006,2748.4,Finance and Insurance
56,West Virginia,57,531,Real estate,Millions of chained 2017 dollars,2006,6136.5,Real Estate and Rental and Leasing
57,West Virginia,58,532-533,Rental and leasing services and lessors of non...,Millions of chained 2017 dollars,2006,558.9,Real Estate and Rental and Leasing
59,West Virginia,60,54,"Professional, scientific, and technical services",Millions of chained 2017 dollars,2006,2824.9,Professional and Business Services
63,West Virginia,64,55,Management of companies and enterprises,Millions of chained 2017 dollars,2006,447.4,Professional and Business Services
64,West Virginia,65,56,Administrative and support and waste managemen...,Millions of chained 2017 dollars,2006,1345.8,Professional and Business Services
68,West Virginia,69,61,Educational services,Millions of chained 2017 dollars,2006,392.0,Private Educational Services

In [11]:
# Compare totals to check differences (<3% is fine for inflation adjusted data)
# Extract official totals
official_totals = sagdp9wv_long[sagdp9wv_long['Description'] == 'All industry total'][['Year', 'GDPReal']].copy()
official_totals = official_totals.rename(columns={'GDPReal': 'OfficialTotal'})

print('Official totals extracted successfully!')

# Exclude 'All industry total' from mapping
mapped_df = sagdp9wv_long[sagdp9wv_long['Description'] != 'All industry total']

print('All industry total excluded successfully!')

# Sum GDPReal by year for mapped industries
mapped_sums = mapped_df.groupby('Year')['GDPReal'].sum().reset_index()
mapped_sums = mapped_sums.rename(columns={'GDPReal': 'MappedTotal'})

print('GDPReal summed successfully!')

# Merge with official totals
compare_totals = pd.merge(official_totals, mapped_sums, on='Year')
compare_totals['Difference'] = compare_totals['MappedTotal'] - compare_totals['OfficialTotal']
compare_totals['PercentDiff'] = compare_totals['Difference'] / compare_totals['OfficialTotal'] * 100

print('Data merged successfully!')

# Show the rows
print(compare_totals.head(20).to_markdown(index=False))

Official totals extracted successfully!
All industry total excluded successfully!
GDPReal summed successfully!
Data merged successfully!
|   Year |   OfficialTotal |   MappedTotal |   Difference |   PercentDiff |
|-------:|----------------:|--------------:|-------------:|--------------:|
|   2006 |         68900   |       70664.4 |       1764.4 |   2.56081     |
|   2007 |         69374.1 |       71104.6 |       1730.5 |   2.49445     |
|   2008 |         70966.8 |       72696.2 |       1729.4 |   2.43691     |
|   2009 |         70886.5 |       72467.2 |       1580.7 |   2.2299      |
|   2010 |         71823.8 |       73420.3 |       1596.5 |   2.2228      |
|   2011 |         73175.2 |       74745.8 |       1570.6 |   2.14636     |
|   2012 |         73124.5 |       74815   |       1690.5 |   2.31181     |
|   2013 |         73949   |       75187.8 |       1238.8 |   1.67521     |
|   2014 |         74111.3 |       74600.2 |        488.9 |   0.659683    |
|   2015 |         74261.4 |       74267.5 |          6.1 |   0.00821423  |
|   2016 |         73513.3 |       73505.3 |         -8   |  -0.0108824   |
|   2017 |         75172.4 |       75172.5 |          0.1 |   0.000133028 |
|   2018 |         77406.5 |       77470.8 |         64.3 |   0.083068    |
|   2019 |         77162.2 |       77203   |         40.8 |   0.0528756   |
|   2020 |         74729.6 |       75356.1 |        626.5 |   0.838356    |
|   2021 |         76230.8 |       76843.5 |        612.7 |   0.803743    |
|   2022 |         77549.1 |       78509.1 |        960   |   1.23793     |
|   2023 |         80364.9 |       81125.2 |        760.3 |   0.94606     |
|   2024 |         82716.5 |       83439   |        722.5 |   0.873465    |

In [12]:
# Pull out All industry total for reference
totals = sagdp9wv_long[
    sagdp9wv_long['Description'] == 'All industry total'
][['Year', 'Description', 'GDPReal']].copy()

print('All industry total extracted successfully!')

# Rename for consistency
totals.rename(columns={'Description': 'Industry'}, inplace=True)

print('All industry total renamed successfully!')

# Remove All industry total from subsectors before grouping
subsectors = sagdp9wv_long[sagdp9wv_long['Description'] != 'All industry total'].copy()
subsectors = subsectors.dropna(subset=['Industry'])

print('All industry total dropped successfully!')

# Sum subsectors by year and mapped industry
grouped = subsectors.groupby(
    ['Year', 'Industry'],
    as_index=False
)['GDPReal'].sum()

print('Subsectors grouped and summed successfully!')

# Add Total Nonfarm to grouped table
total_nonfarm = totals.copy()
total_nonfarm['Industry'] = 'Total Nonfarm'
sagdp9wv_grouped = pd.concat([grouped, total_nonfarm[['Year','Industry','GDPReal']]], ignore_index=True)

print('Total Nonfarm added successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_grouped.shape)
sagdp9wv_grouped.head()

All industry total extracted successfully!
All industry total renamed successfully!
All industry total dropped successfully!
Subsectors grouped and summed successfully!
Total Nonfarm added successfully!
Data check:
Data shape: (266, 3)

   Year                           Industry  GDPReal
0  2006                       Construction   3667.8
1  2006              Finance and Insurance   2748.4
2  2006                         Government  12513.0
3  2006  Health Care and Social Assistance   6346.2
4  2006                        Information   1181.1

In [13]:
# Round gdp values
sagdp9wv_grouped['GDPReal'] = sagdp9wv_grouped['GDPReal'].round(1)

print('GDPReal rounded successfully!')

# Sort by Year and IndustryName
sagdp9wv_grouped = sagdp9wv_grouped.sort_values(
    ['Year', 'Industry']
)

print('Data sorted successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_grouped.shape)
sagdp9wv_grouped.head()

GDPReal rounded successfully!
Data sorted successfully!
Data check:
Data shape: (266, 3)

   Year                           Industry  GDPReal
0  2006                       Construction   3667.8
1  2006              Finance and Insurance   2748.4
2  2006                         Government  12513.0
3  2006  Health Care and Social Assistance   6346.2
4  2006                        Information   1181.1

In [14]:
# Exclude Total Nonfarm from industry share calculation
top_level_rows = sagdp9wv_grouped[sagdp9wv_grouped['Industry'] != 'Total Nonfarm'].copy()

print('Total Nonfarm excluded successfully!')

# Compute total GDP per year from top-level industries
total_gdp_per_year = top_level_rows.groupby('Year')['GDPReal'].sum().reset_index()
total_gdp_per_year.rename(columns={'GDPReal': 'TotalGDP'}, inplace=True)

print('Total GDP per year computed successfully!')

# Merge TotalGDP back into top-level rows
sagdp9wv_clean = top_level_rows.merge(total_gdp_per_year, on='Year', how='left')

print('Total GDP merged successfully!')

# Compute industry shares
sagdp9wv_clean['IndustryShare'] = sagdp9wv_clean['GDPReal'] / sagdp9wv_clean['TotalGDP']
sagdp9wv_clean['IndustrySharePct'] = sagdp9wv_clean['IndustryShare'] * 100

print('Industry shares computed successfully!')

# Round GDP and shares for readability
sagdp9wv_clean['GDPReal'] = sagdp9wv_clean['GDPReal'].round(1)
sagdp9wv_clean['IndustryShare'] = sagdp9wv_clean['IndustryShare'].round(6)
sagdp9wv_clean['IndustrySharePct'] = sagdp9wv_clean['IndustrySharePct'].round(2)

print('GDP and shares rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Total Nonfarm excluded successfully!
Total GDP per year computed successfully!
Total GDP merged successfully!
Industry shares computed successfully!
GDP and shares rounded successfully!
Data check:
Data shape: (247, 6)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct
0,2006,Construction,3667.8,70664.4,0.051904,5.19
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89
2,2006,Government,12513.0,70664.4,0.177076,17.71
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98
4,2006,Information,1181.1,70664.4,0.016714,1.67

In [15]:
# Sum GDPReal for each year across top-level industries only (exclude Total Nonfarm)
yearly_totals = sagdp9wv_clean.groupby('Year')['GDPReal'].sum().reset_index()

print('Yearly totals computed successfully!')

print(yearly_totals)

Yearly totals computed successfully!
    Year  GDPReal
0   2006  70664.4
1   2007  71104.6
2   2008  72696.2
3   2009  72467.2
4   2010  73420.3
5   2011  74745.8
6   2012  74815.0
7   2013  75187.8
8   2014  74600.2
9   2015  74267.5
10  2016  73505.3
11  2017  75172.5
12  2018  77470.8
13  2019  77203.0
14  2020  75356.1
15  2021  76843.5
16  2022  78509.1
17  2023  81125.2
18  2024  83439.0

In [16]:
# Calculate year-over-year industry GDP growth
sagdp9wv_clean['IndustryGDPGrowth'] = sagdp9wv_clean.groupby('Industry')['GDPReal'].pct_change() * 100

print('Industry GDP growth computed successfully!')

# Round industry growth for readability
sagdp9wv_clean['IndustryGDPGrowth'] = sagdp9wv_clean['IndustryGDPGrowth'].round(2)

print('Industry growth rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Industry GDP growth computed successfully!
Industry growth rounded successfully!
Data check:
Data shape: (247, 7)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN

In [17]:
# Calculate total GDP per year (unique yearly values)
state_growth = (
    sagdp9wv_clean[['Year', 'TotalGDP']]
    .drop_duplicates()
    .sort_values('Year')
)

print('Total GDP per year calculated successfully!')

# Calculate year-over-year growth
state_growth['StateGDPGrowth'] = (
    state_growth['TotalGDP'].pct_change() * 100
)

print('State GDP growth calculated successfully!')

# Round for readability
state_growth['StateGDPGrowth'] = state_growth['StateGDPGrowth'].round(2)

print('State GDP growth rounded successfully!')

# Merge back into main dataframe
sagdp9wv_clean = sagdp9wv_clean.merge(
    state_growth[['Year', 'StateGDPGrowth']],
    on='Year',
    how='left'
)

print('State GDP growth merged successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Total GDP per year calculated successfully!
State GDP growth calculated successfully!
State GDP growth rounded successfully!
State GDP growth merged successfully!
Data check:
Data shape: (247, 8)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN

In [18]:
# Calculate contribution to growth
# Shift industry share back one year
sagdp9wv_clean['PriorShare'] = (
    sagdp9wv_clean
    .groupby('Industry')['IndustryShare']
    .shift(1)
)

print('Prior share calculated successfully!')

# Compute contribution to state growth
sagdp9wv_clean['GrowthContribution'] = (
    sagdp9wv_clean['PriorShare'] *
    sagdp9wv_clean['IndustryGDPGrowth']
)

print('Growth contribution calculated successfully!')

# Round for readability
sagdp9wv_clean['GrowthContribution'] = sagdp9wv_clean['GrowthContribution'].round(2)

print('Growth contribution rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Prior share calculated successfully!
Growth contribution calculated successfully!
Growth contribution rounded successfully!
Data check:
Data shape: (247, 10)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth,PriorShare,GrowthContribution
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN,NaN,NaN
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN,NaN,NaN
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN,NaN,NaN
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN,NaN,NaN
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN,NaN,NaN

In [19]:
# Calculate industry concentration (HHI) in 0-10,000 scale
sagdp9wv_clean['IndustryConcentration'] = (sagdp9wv_clean['IndustryShare']*100) ** 2

print('Industry concentration calculated successfully!')

# Compute HHI per year
hhi_by_year = (
    sagdp9wv_clean
    .groupby('Year')['IndustryConcentration']
    .sum()
    .reset_index()
)

print('HHI per year calculated successfully!')

# Round for readability
sagdp9wv_clean['IndustryConcentration'] = sagdp9wv_clean['IndustryConcentration'].round(1)

print('Industry concentration rounded successfully!')

# Check the result
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Industry concentration calculated successfully!
HHI per year calculated successfully!
Industry concentration rounded successfully!
Data check:
Data shape: (247, 11)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth,PriorShare,GrowthContribution,IndustryConcentration
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN,NaN,NaN,26.9
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN,NaN,NaN,15.1
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN,NaN,NaN,313.6
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN,NaN,NaN,80.7
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN,NaN,NaN,2.8

In [20]:
# Compute 3-year rolling average growth per industry
sagdp9wv_clean['Growth3yrAvg'] = (
    sagdp9wv_clean
    .groupby('Industry')['IndustryGDPGrowth']
    .rolling(3)
    .mean()
    .reset_index(level=0, drop=True)
)

print('3-year rolling average growth calculated successfully!')

# Round for readability
sagdp9wv_clean['Growth3yrAvg'] = sagdp9wv_clean['Growth3yrAvg'].round(2)

print('3-year rolling average growth rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

3-year rolling average growth calculated successfully!
3-year rolling average growth rounded successfully!
Data check:
Data shape: (247, 12)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth,PriorShare,GrowthContribution,IndustryConcentration,Growth3yrAvg
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN,NaN,NaN,26.9,NaN
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN,NaN,NaN,15.1,NaN
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN,NaN,NaN,313.6,NaN
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN,NaN,NaN,80.7,NaN
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN,NaN,NaN,2.8,NaN

In [21]:
# Calculate volatility per industry
sagdp9wv_clean['GrowthVolatility'] = (
    sagdp9wv_clean
    .groupby('Industry')['IndustryGDPGrowth']
    .transform('std')
)

print('Growth volatility calculated successfully!')

# Round for readability
sagdp9wv_clean['GrowthVolatility'] = sagdp9wv_clean['GrowthVolatility'].round(2)

print('Growth volatility rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Growth volatility calculated successfully!
Growth volatility rounded successfully!
Data check:
Data shape: (247, 13)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth,PriorShare,GrowthContribution,IndustryConcentration,Growth3yrAvg,GrowthVolatility
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN,NaN,NaN,26.9,NaN,13.22
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN,NaN,NaN,15.1,NaN,4.41
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN,NaN,NaN,313.6,NaN,1.39
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN,NaN,NaN,80.7,NaN,2.33
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN,NaN,NaN,2.8,NaN,6.02

In [22]:
# Calculate industry rank by size (structural view)
sagdp9wv_clean['IndustryRank'] = (
    sagdp9wv_clean
    .groupby('Year')['GDPReal']
    .rank(ascending=False, method='min')
)

print('Industry rank calculated successfully!')

# Convert rank to integer
sagdp9wv_clean['IndustryRank'] = sagdp9wv_clean['IndustryRank'].astype(int)

print('Industry rank converted to integer successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.head()

Industry rank calculated successfully!
Industry rank converted to integer successfully!
Data check:
Data shape: (247, 14)

,Year,Industry,GDPReal,TotalGDP,IndustryShare,IndustrySharePct,IndustryGDPGrowth,StateGDPGrowth,PriorShare,GrowthContribution,IndustryConcentration,Growth3yrAvg,GrowthVolatility,IndustryRank
0,2006,Construction,3667.8,70664.4,0.051904,5.19,NaN,NaN,NaN,NaN,26.9,NaN,13.22,8
1,2006,Finance and Insurance,2748.4,70664.4,0.038894,3.89,NaN,NaN,NaN,NaN,15.1,NaN,4.41,10
2,2006,Government,12513.0,70664.4,0.177076,17.71,NaN,NaN,NaN,NaN,313.6,NaN,1.39,2
3,2006,Health Care and Social Assistance,6346.2,70664.4,0.089808,8.98,NaN,NaN,NaN,NaN,80.7,NaN,2.33,6
4,2006,Information,1181.1,70664.4,0.016714,1.67,NaN,NaN,NaN,NaN,2.8,NaN,6.02,12

In [23]:
# Rename GDPReal column to RealGDP
sagdp9wv_clean = sagdp9wv_clean.rename(columns={'GDPReal': 'RealGDP'})

print('Column renamed successfully!')

Column renamed successfully!

In [24]:
# Insert underscores into column names
sagdp9wv_clean.columns = [
    re.sub(
        r'(?<=[a-z])(?=[A-Z])'        # lower -> Upper
        r'|(?<=[A-Z])(?=[A-Z][a-z])'  # acronym -> Word
        r'|(?<=[a-zA-Z])(?=[0-9])'    # letter -> number
        r'|(?<=[0-9])(?=[A-Z])',      # number -> Upper ONLY
        '_',
        col
    )
    for col in sagdp9wv_clean.columns
]

print('Underscores inserted successfully!')

# Data check
print('Data check:')
print('Data shape:', sagdp9wv_clean.shape)
sagdp9wv_clean.info()

Underscores inserted successfully!
Data check:
Data shape: (247, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    247 non-null    Int64
 1   Industry                247 non-null    object
 2   Real_GDP                247 non-null    float64
 3   Total_GDP               247 non-null    float64
 4   Industry_Share          247 non-null    float64
 5   Industry_Share_Pct      247 non-null    float64
 6   Industry_GDP_Growth     234 non-null    float64
 7   State_GDP_Growth        234 non-null    float64
 8   Prior_Share             234 non-null    float64
 9   Growth_Contribution     234 non-null    float64
 10  Industry_Concentration  247 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       247 non-null    float64
 13  Industry_Rank           247 non-null    int64
dtypes: Int64(1), float64(11), int64(1), object(1)
memory usage: 27.4+ KB

In [25]:
# Check for duplicates
print('Number of duplicate rows:', sagdp9wv_clean.duplicated().sum())

# Reset index
sagdp9wv_clean = sagdp9wv_clean.reset_index(drop=True)

print('Index reset successfully!')

Number of duplicate rows: 0
Index reset successfully!

In [26]:
# Save df to csv
sagdp9wv_clean.to_csv('../../../workspace/nf-insights-project/data_clean/sagdp9wv_clean.csv', index=False)

print('CSV saved successfully!')

CSV saved successfully!