BEA SAGDP9_WV + BLS Employment dataset merging.

In [52]:
# Import libraries
import pandas as pd

print('Libraries imported successfully')

Libraries imported successfully

In [53]:
# Read in data
sagdp9wv_df = pd.read_csv('../../../workspace/nf-insights-project/data_clean/sagdp9wv_clean.csv', parse_dates=['Year'], low_memory=False)
blsemp_df = pd.read_csv('../../../workspace/nf-insights-project/data_clean/bls_employ_clean.csv', parse_dates=['Year'], low_memory=False)

print('CSVs read successfully!')

# Data check
print('Data check:')
print(sagdp9wv_df.head())
print(blsemp_df.head())

CSVs read successfully!
Data check:
        Year                           Industry  Real_GDP  Total_GDP  \
0 2006-01-01                       Construction    3667.8    70664.4
1 2006-01-01              Finance and Insurance    2748.4    70664.4
2 2006-01-01                         Government   12513.0    70664.4
3 2006-01-01  Health Care and Social Assistance    6346.2    70664.4
4 2006-01-01                        Information    1181.1    70664.4

   Industry_Share  Industry_Share_Pct  Industry_GDP_Growth  State_GDP_Growth  \
0        0.051904                5.19                  NaN               NaN
1        0.038894                3.89                  NaN               NaN
2        0.177076               17.71                  NaN               NaN
3        0.089808                8.98                  NaN               NaN
4        0.016714                1.67                  NaN               NaN

   Prior_Share  Growth_Contribution  Industry_Concentration  Growth_3yr_Avg  \
0          NaN                  NaN                    26.9             NaN
1          NaN                  NaN                    15.1             NaN
2          NaN                  NaN                   313.6             NaN
3          NaN                  NaN                    80.7             NaN
4          NaN                  NaN                     2.8             NaN

   Growth_Volatility  Industry_Rank
0              13.22              8
1               4.41             10
2               1.39              2
3               2.33              6
4               6.02             12
        Year                           Industry  Employment  YoY_Growth  \
0 2006-01-01                       Construction     39425.0         NaN
1 2006-01-01              Finance and Insurance     21250.0         NaN
2 2006-01-01                         Government    145608.3         NaN
3 2006-01-01  Health Care and Social Assistance    102408.3         NaN
4 2006-01-01                        Information     11508.3         NaN

   Yearly_Change  Total_Employment_Year  Industry_Share_Pct  \
0            NaN               722683.2                5.46
1            NaN               722683.2                2.94
2            NaN               722683.2               20.15
3            NaN               722683.2               14.17
4            NaN               722683.2                1.59

   YoY_Growth_3yr_Avg  Top3_Share_Pct     HHI  Industry_Rank
0                 NaN            54.0  1299.3              7
1                 NaN            54.0  1299.3             10
2                 NaN            54.0  1299.3              1
3                 NaN            54.0  1299.3              3
4                 NaN            54.0  1299.3             11

In [54]:
# Data check
print('Data check:')
print(sagdp9wv_df.info())
print(blsemp_df.info())

Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    247 non-null    datetime64[ns]
 1   Industry                247 non-null    object
 2   Real_GDP                247 non-null    float64
 3   Total_GDP               247 non-null    float64
 4   Industry_Share          247 non-null    float64
 5   Industry_Share_Pct      247 non-null    float64
 6   Industry_GDP_Growth     234 non-null    float64
 7   State_GDP_Growth        234 non-null    float64
 8   Prior_Share             234 non-null    float64
 9   Growth_Contribution     234 non-null    float64
 10  Industry_Concentration  247 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       247 non-null    float64
 13  Industry_Rank           247 non-null    int64
dtypes: datetime64[ns](1), float64(11), int64(1), object(1)
memory usage: 27.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   260 non-null    datetime64[ns]
 1   Industry               260 non-null    object
 2   Employment             260 non-null    float64
 3   YoY_Growth             247 non-null    float64
 4   Yearly_Change          247 non-null    float64
 5   Total_Employment_Year  260 non-null    float64
 6   Industry_Share_Pct     260 non-null    float64
 7   YoY_Growth_3yr_Avg     221 non-null    float64
 8   Top3_Share_Pct         260 non-null    float64
 9   HHI                    260 non-null    float64
 10  Industry_Rank          260 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(1)
memory usage: 22.5+ KB
None

In [55]:
# Check for matching industries
print(set(sagdp9wv_df['Industry']) - set(blsemp_df['Industry']))
print(set(blsemp_df['Industry']) - set(sagdp9wv_df['Industry']))

set()
set()

In [56]:
# Filter for years 2009-2024 before merging
sagdp9wv_df = sagdp9wv_df[(sagdp9wv_df['Year'].dt.year >= 2009) & 
                                (sagdp9wv_df['Year'].dt.year <= 2024)]
blsemp_df = blsemp_df[(blsemp_df['Year'].dt.year >= 2009) & 
                            (blsemp_df['Year'].dt.year <= 2024)]

print('Filtered successfully!')

# Data check
print('Data check:')
print(sagdp9wv_df.info())
print(blsemp_df.info())

Filtered successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 39 to 246
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share          208 non-null    float64
 5   Industry_Share_Pct      208 non-null    float64
 6   Industry_GDP_Growth     208 non-null    float64
 7   State_GDP_Growth        208 non-null    float64
 8   Prior_Share             208 non-null    float64
 9   Growth_Contribution     208 non-null    float64
 10  Industry_Concentration  208 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       208 non-null    float64
 13  Industry_Rank           208 non-null    int64
dtypes: datetime64[ns](1), float64(11), int64(1), object(1)
memory usage: 24.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 39 to 246
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   208 non-null    datetime64[ns]
 1   Industry               208 non-null    object
 2   Employment             208 non-null    float64
 3   YoY_Growth             208 non-null    float64
 4   Yearly_Change          208 non-null    float64
 5   Total_Employment_Year  208 non-null    float64
 6   Industry_Share_Pct     208 non-null    float64
 7   YoY_Growth_3yr_Avg     208 non-null    float64
 8   Top3_Share_Pct         208 non-null    float64
 9   HHI                    208 non-null    float64
 10  Industry_Rank          208 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(1)
memory usage: 19.5+ KB
None

In [57]:
# Merge dataframes
beagdp_blsemp = pd.merge(sagdp9wv_df, blsemp_df, how='inner', on=['Year', 'Industry'], suffixes=('_BEA', '_BLS'))

print('Merged successfully!')

# Reset index
beagdp_blsemp = beagdp_blsemp.reset_index(drop=True)

print('Index reset successfully!')  

# Data check
print('Data check:')
print('Data shape:', beagdp_blsemp.shape)
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Merged successfully!
Index reset successfully!
Data check:
Data shape: (208, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share          208 non-null    float64
 5   Industry_Share_Pct_BEA  208 non-null    float64
 6   Industry_GDP_Growth     208 non-null    float64
 7   State_GDP_Growth        208 non-null    float64
 8   Prior_Share             208 non-null    float64
 9   Growth_Contribution     208 non-null    float64
 10  Industry_Concentration  208 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       208 non-null    float64
 13  Industry_Rank_BEA       208 non-null    int64
 14  Employment              208 non-null    float64
 15  YoY_Growth              208 non-null    float64
 16  Yearly_Change           208 non-null    float64
 17  Total_Employment_Year   208 non-null    float64
 18  Industry_Share_Pct_BLS  208 non-null    float64
 19  YoY_Growth_3yr_Avg      208 non-null    float64
 20  Top3_Share_Pct          208 non-null    float64
 21  HHI                     208 non-null    float64
 22  Industry_Rank_BLS       208 non-null    int64
dtypes: datetime64[ns](1), float64(19), int64(2), object(1)
memory usage: 37.5+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share,Industry_Share_Pct_BEA,Industry_GDP_Growth,State_GDP_Growth,Prior_Share,Growth_Contribution,...,Industry_Rank_BEA,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct_BLS,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank_BLS
0,2009-01-01,Construction,3570.7,72467.2,0.049273,4.93,-3.97,-0.32,0.051150,-0.20,...,8,34075.0,-12.42,-4833.3,710933.3,4.79,-4.58,55.6,1335.8,7
1,2009-01-01,Finance and Insurance,2946.8,72467.2,0.040664,4.07,9.98,-0.32,0.036857,0.37,...,9,19775.0,-4.12,-850.0,710933.3,2.78,-2.36,55.6,1335.8,10
2,2009-01-01,Government,12834.8,72467.2,0.177112,17.71,1.95,-0.32,0.173175,0.34,...,1,150025.0,1.71,2525.0,710933.3,21.10,1.01,55.6,1335.8,1
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,0.094341,9.43,3.15,-0.32,0.091173,0.29,...,6,109241.7,2.42,2583.4,710933.3,15.37,2.18,55.6,1335.8,3
4,2009-01-01,Information,1263.6,72467.2,0.017437,1.74,-4.86,-0.32,0.018271,-0.09,...,12,10433.3,-6.50,-725.0,710933.3,1.47,-3.19,55.6,1335.8,11

In [58]:
# Round for readability (2 decimals)
pct_cols = [
    'Industry_Share',
    'Industry_Share_Pct_BEA',
    'Industry_Share_Pct_BLS',
    'Industry_GDP_Growth',
    'State_GDP_Growth',
    'Prior_Share',
    'Growth_Contribution',
    'Growth_3yr_Avg',
    'YoY_Growth',
    'YoY_Growth_3yr_Avg',
    'Top3_Share_Pct'
]

beagdp_blsemp[pct_cols] = beagdp_blsemp[pct_cols].round(2)

print('Rounded to 2 decimals successfully!')

# Round for readability (1 decimal)
conc_cols = ['HHI','Industry_Concentration','Growth_Volatility']

beagdp_blsemp[conc_cols] = beagdp_blsemp[conc_cols].round(1)

print('Rounded to 1 decimal successfully!')

# Convert to int
beagdp_blsemp['Employment'] = beagdp_blsemp['Employment'].astype(int)
beagdp_blsemp['Total_Employment_Year'] = beagdp_blsemp['Total_Employment_Year'].astype(int)
beagdp_blsemp['Yearly_Change'] = beagdp_blsemp['Yearly_Change'].astype(int)

print('Converted to int successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Rounded to 2 decimals successfully!
Rounded to 1 decimal successfully!
Converted to int successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share          208 non-null    float64
 5   Industry_Share_Pct_BEA  208 non-null    float64
 6   Industry_GDP_Growth     208 non-null    float64
 7   State_GDP_Growth        208 non-null    float64
 8   Prior_Share             208 non-null    float64
 9   Growth_Contribution     208 non-null    float64
 10  Industry_Concentration  208 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       208 non-null    float64
 13  Industry_Rank_BEA       208 non-null    int64
 14  Employment              208 non-null    int64
 15  YoY_Growth              208 non-null    float64
 16  Yearly_Change           208 non-null    int64
 17  Total_Employment_Year   208 non-null    int64
 18  Industry_Share_Pct_BLS  208 non-null    float64
 19  YoY_Growth_3yr_Avg      208 non-null    float64
 20  Top3_Share_Pct          208 non-null    float64
 21  HHI                     208 non-null    float64
 22  Industry_Rank_BLS       208 non-null    int64
dtypes: datetime64[ns](1), float64(16), int64(5), object(1)
memory usage: 37.5+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share,Industry_Share_Pct_BEA,Industry_GDP_Growth,State_GDP_Growth,Prior_Share,Growth_Contribution,...,Industry_Rank_BEA,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct_BLS,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank_BLS
0,2009-01-01,Construction,3570.7,72467.2,0.05,4.93,-3.97,-0.32,0.05,-0.20,...,8,34075,-12.42,-4833,710933,4.79,-4.58,55.6,1335.8,7
1,2009-01-01,Finance and Insurance,2946.8,72467.2,0.04,4.07,9.98,-0.32,0.04,0.37,...,9,19775,-4.12,-850,710933,2.78,-2.36,55.6,1335.8,10
2,2009-01-01,Government,12834.8,72467.2,0.18,17.71,1.95,-0.32,0.17,0.34,...,1,150025,1.71,2525,710933,21.10,1.01,55.6,1335.8,1
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,0.09,9.43,3.15,-0.32,0.09,0.29,...,6,109241,2.42,2583,710933,15.37,2.18,55.6,1335.8,3
4,2009-01-01,Information,1263.6,72467.2,0.02,1.74,-4.86,-0.32,0.02,-0.09,...,12,10433,-6.50,-725,710933,1.47,-3.19,55.6,1335.8,11

In [59]:
# Calculate GDP per worker (productivity)
beagdp_blsemp['GDP_per_Worker'] = (beagdp_blsemp['Real_GDP'] * 1_000_000) / beagdp_blsemp['Employment']

print('GDP per worker calculated successfully!')

# Round for readability
beagdp_blsemp['GDP_per_Worker'] = beagdp_blsemp['GDP_per_Worker'].round(2)

print('Values rounded successfully!')

# Convert to int
beagdp_blsemp['GDP_per_Worker'] = beagdp_blsemp['GDP_per_Worker'].astype(int)

print('Converted to int successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

GDP per worker calculated successfully!
Values rounded successfully!
Converted to int successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share          208 non-null    float64
 5   Industry_Share_Pct_BEA  208 non-null    float64
 6   Industry_GDP_Growth     208 non-null    float64
 7   State_GDP_Growth        208 non-null    float64
 8   Prior_Share             208 non-null    float64
 9   Growth_Contribution     208 non-null    float64
 10  Industry_Concentration  208 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       208 non-null    float64
 13  Industry_Rank_BEA       208 non-null    int64
 14  Employment              208 non-null    int64
 15  YoY_Growth              208 non-null    float64
 16  Yearly_Change           208 non-null    int64
 17  Total_Employment_Year   208 non-null    int64
 18  Industry_Share_Pct_BLS  208 non-null    float64
 19  YoY_Growth_3yr_Avg      208 non-null    float64
 20  Top3_Share_Pct          208 non-null    float64
 21  HHI                     208 non-null    float64
 22  Industry_Rank_BLS       208 non-null    int64
 23  GDP_per_Worker          208 non-null    int64
dtypes: datetime64[ns](1), float64(16), int64(6), object(1)
memory usage: 39.1+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share,Industry_Share_Pct_BEA,Industry_GDP_Growth,State_GDP_Growth,Prior_Share,Growth_Contribution,...,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct_BLS,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank_BLS,GDP_per_Worker
0,2009-01-01,Construction,3570.7,72467.2,0.05,4.93,-3.97,-0.32,0.05,-0.20,...,34075,-12.42,-4833,710933,4.79,-4.58,55.6,1335.8,7,104789
1,2009-01-01,Finance and Insurance,2946.8,72467.2,0.04,4.07,9.98,-0.32,0.04,0.37,...,19775,-4.12,-850,710933,2.78,-2.36,55.6,1335.8,10,149016
2,2009-01-01,Government,12834.8,72467.2,0.18,17.71,1.95,-0.32,0.17,0.34,...,150025,1.71,2525,710933,21.10,1.01,55.6,1335.8,1,85551
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,0.09,9.43,3.15,-0.32,0.09,0.29,...,109241,2.42,2583,710933,15.37,2.18,55.6,1335.8,3,62582
4,2009-01-01,Information,1263.6,72467.2,0.02,1.74,-4.86,-0.32,0.02,-0.09,...,10433,-6.50,-725,710933,1.47,-3.19,55.6,1335.8,11,121115

In [60]:
# Calculate output vs employment gap
beagdp_blsemp['Output_Gap'] = beagdp_blsemp['Industry_Share_Pct_BEA'] - beagdp_blsemp['Industry_Share_Pct_BLS']

print('Output vs employment gap calculated successfully!')

# Round for readability
beagdp_blsemp['Output_Gap'] = beagdp_blsemp['Output_Gap'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Output vs employment gap calculated successfully!
Values rounded successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    208 non-null    datetime64[ns]
 1   Industry                208 non-null    object
 2   Real_GDP                208 non-null    float64
 3   Total_GDP               208 non-null    float64
 4   Industry_Share          208 non-null    float64
 5   Industry_Share_Pct_BEA  208 non-null    float64
 6   Industry_GDP_Growth     208 non-null    float64
 7   State_GDP_Growth        208 non-null    float64
 8   Prior_Share             208 non-null    float64
 9   Growth_Contribution     208 non-null    float64
 10  Industry_Concentration  208 non-null    float64
 11  Growth_3yr_Avg          208 non-null    float64
 12  Growth_Volatility       208 non-null    float64
 13  Industry_Rank_BEA       208 non-null    int64
 14  Employment              208 non-null    int64
 15  YoY_Growth              208 non-null    float64
 16  Yearly_Change           208 non-null    int64
 17  Total_Employment_Year   208 non-null    int64
 18  Industry_Share_Pct_BLS  208 non-null    float64
 19  YoY_Growth_3yr_Avg      208 non-null    float64
 20  Top3_Share_Pct          208 non-null    float64
 21  HHI                     208 non-null    float64
 22  Industry_Rank_BLS       208 non-null    int64
 23  GDP_per_Worker          208 non-null    int64
 24  Output_Gap              208 non-null    float64
dtypes: datetime64[ns](1), float64(17), int64(6), object(1)
memory usage: 40.8+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share,Industry_Share_Pct_BEA,Industry_GDP_Growth,State_GDP_Growth,Prior_Share,Growth_Contribution,...,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct_BLS,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank_BLS,GDP_per_Worker,Output_Gap
0,2009-01-01,Construction,3570.7,72467.2,0.05,4.93,-3.97,-0.32,0.05,-0.20,...,-12.42,-4833,710933,4.79,-4.58,55.6,1335.8,7,104789,0.14
1,2009-01-01,Finance and Insurance,2946.8,72467.2,0.04,4.07,9.98,-0.32,0.04,0.37,...,-4.12,-850,710933,2.78,-2.36,55.6,1335.8,10,149016,1.29
2,2009-01-01,Government,12834.8,72467.2,0.18,17.71,1.95,-0.32,0.17,0.34,...,1.71,2525,710933,21.10,1.01,55.6,1335.8,1,85551,-3.39
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,0.09,9.43,3.15,-0.32,0.09,0.29,...,2.42,2583,710933,15.37,2.18,55.6,1335.8,3,62582,-5.94
4,2009-01-01,Information,1263.6,72467.2,0.02,1.74,-4.86,-0.32,0.02,-0.09,...,-6.50,-725,710933,1.47,-3.19,55.6,1335.8,11,121115,0.27

In [61]:
# Calculate growth contribution vs employment growth to see misalignment
beagdp_blsemp['Employment_vs_Growth_Alignment'] = beagdp_blsemp['YoY_Growth'] * beagdp_blsemp['Growth_Contribution']

print('Growth contribution vs employment growth misalignment calculated successfully!')

# Round for readability
beagdp_blsemp['Employment_vs_Growth_Alignment'] = beagdp_blsemp['Employment_vs_Growth_Alignment'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print(beagdp_blsemp.info())
beagdp_blsemp.head()

Growth contribution vs employment growth misalignment calculated successfully!
Values rounded successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            208 non-null    datetime64[ns]
 1   Industry                        208 non-null    object
 2   Real_GDP                        208 non-null    float64
 3   Total_GDP                       208 non-null    float64
 4   Industry_Share                  208 non-null    float64
 5   Industry_Share_Pct_BEA          208 non-null    float64
 6   Industry_GDP_Growth             208 non-null    float64
 7   State_GDP_Growth                208 non-null    float64
 8   Prior_Share                     208 non-null    float64
 9   Growth_Contribution             208 non-null    float64
 10  Industry_Concentration          208 non-null    float64
 11  Growth_3yr_Avg                  208 non-null    float64
 12  Growth_Volatility               208 non-null    float64
 13  Industry_Rank_BEA               208 non-null    int64
 14  Employment                      208 non-null    int64
 15  YoY_Growth                      208 non-null    float64
 16  Yearly_Change                   208 non-null    int64
 17  Total_Employment_Year           208 non-null    int64
 18  Industry_Share_Pct_BLS          208 non-null    float64
 19  YoY_Growth_3yr_Avg              208 non-null    float64
 20  Top3_Share_Pct                  208 non-null    float64
 21  HHI                             208 non-null    float64
 22  Industry_Rank_BLS               208 non-null    int64
 23  GDP_per_Worker                  208 non-null    int64
 24  Output_Gap                      208 non-null    float64
 25  Employment_vs_Growth_Alignment  208 non-null    float64
dtypes: datetime64[ns](1), float64(18), int64(6), object(1)
memory usage: 42.4+ KB
None

,Year,Industry,Real_GDP,Total_GDP,Industry_Share,Industry_Share_Pct_BEA,Industry_GDP_Growth,State_GDP_Growth,Prior_Share,Growth_Contribution,...,Yearly_Change,Total_Employment_Year,Industry_Share_Pct_BLS,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank_BLS,GDP_per_Worker,Output_Gap,Employment_vs_Growth_Alignment
0,2009-01-01,Construction,3570.7,72467.2,0.05,4.93,-3.97,-0.32,0.05,-0.20,...,-4833,710933,4.79,-4.58,55.6,1335.8,7,104789,0.14,2.48
1,2009-01-01,Finance and Insurance,2946.8,72467.2,0.04,4.07,9.98,-0.32,0.04,0.37,...,-850,710933,2.78,-2.36,55.6,1335.8,10,149016,1.29,-1.52
2,2009-01-01,Government,12834.8,72467.2,0.18,17.71,1.95,-0.32,0.17,0.34,...,2525,710933,21.10,1.01,55.6,1335.8,1,85551,-3.39,0.58
3,2009-01-01,Health Care and Social Assistance,6836.6,72467.2,0.09,9.43,3.15,-0.32,0.09,0.29,...,2583,710933,15.37,2.18,55.6,1335.8,3,62582,-5.94,0.70
4,2009-01-01,Information,1263.6,72467.2,0.02,1.74,-4.86,-0.32,0.02,-0.09,...,-725,710933,1.47,-3.19,55.6,1335.8,11,121115,0.27,0.58

In [62]:
# Reset index
beagdp_blsemp_clean = beagdp_blsemp.reset_index(drop=True)

print('Index reset successfully!')

# Save to CSV
beagdp_blsemp_clean.to_csv('../../../workspace/nf-insights-project/data_clean/beagdp_blsemp_merge_clean.csv', index=False)

print('CSV saved successfully!')

Index reset successfully!
CSV saved successfully!