BLS Industry Employment Data Exploration and Cleaning

In [45]:
# Import libraries
import pandas as pd

print('Libraries imported successfully!')

Libraries imported successfully!

In [46]:
# Read in bls employment data csv file
blsemp_df = pd.read_csv('../../../workspace/nf-insights-project/data_raw/bls_employ_data_raw.csv')

print('CSV read successfully!')

# Data check
blsemp_df.head()

CSV read successfully!

              Series ID  Year Period     Label  Value
0  SMU54000000000000001  2006    M01  2006 Jan  706.1
1  SMU54000000000000001  2006    M02  2006 Feb  709.0
2  SMU54000000000000001  2006    M03  2006 Mar  718.2
3  SMU54000000000000001  2006    M04  2006 Apr  720.9
4  SMU54000000000000001  2006    M05  2006 May  736.4

In [47]:
# Data check
print('Data check:')
print('Data shape:', blsemp_df.shape)
print(blsemp_df.info())
blsemp_df.columns

Data check:
Data shape: (3360, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3360 entries, 0 to 3359
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Series ID  3360 non-null   object
 1   Year       3360 non-null   int64
 2   Period     3360 non-null   object
 3   Label      3360 non-null   object
 4   Value      3360 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 131.4+ KB
None

Index(['Series ID', 'Year', 'Period', 'Label', 'Value'], dtype='object')

In [48]:
# Pull unique Series ID's
print('Unique Series IDs pulled successfully!')
blsemp_df['Series ID'].unique()

Unique Series IDs pulled successfully!

array(['SMU54000000000000001', 'SMU54000001000000001',
       'SMU54000002000000001', 'SMU54000003000000001',
       'SMU54000004000000001', 'SMU54000005000000001',
       'SMU54000005552000001', 'SMU54000005553000001',
       'SMU54000006000000001', 'SMU54000006561000001',
       'SMU54000006562000001', 'SMU54000007000000001',
       'SMU54000008000000001', 'SMU54000009000000001'], dtype=object)

In [49]:
# Create dictionary of Series ID's to industry names
series_map = {
    'SMU54000000000000001': 'Total Nonfarm',
    'SMU54000001000000001': 'Mining and Logging',
    'SMU54000002000000001': 'Construction',
    'SMU54000003000000001': 'Manufacturing',
    'SMU54000004000000001': 'Trade, Transportation, and Utilities',
    'SMU54000005000000001': 'Information',
    'SMU54000005552000001': 'Finance and Insurance',
    'SMU54000005553000001': 'Real Estate and Rental and Leasing',
    'SMU54000006000000001': 'Professional and Business Services',
    'SMU54000006561000001': 'Private Educational Services',
    'SMU54000006562000001': 'Health Care and Social Assistance',
    'SMU54000007000000001': 'Leisure and Hospitality',
    'SMU54000008000000001': 'Other Services',
    'SMU54000009000000001': 'Government'
}

# Map Series ID's to industry names
blsemp_df['Industry'] = blsemp_df['Series ID'].map(series_map)

print('Series IDs mapped successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_df.shape)
blsemp_df.head()

Series IDs mapped successfully!
Data check:
Data shape: (3360, 6)

              Series ID  Year Period     Label  Value       Industry
0  SMU54000000000000001  2006    M01  2006 Jan  706.1  Total Nonfarm
1  SMU54000000000000001  2006    M02  2006 Feb  709.0  Total Nonfarm
2  SMU54000000000000001  2006    M03  2006 Mar  718.2  Total Nonfarm
3  SMU54000000000000001  2006    M04  2006 Apr  720.9  Total Nonfarm
4  SMU54000000000000001  2006    M05  2006 May  736.4  Total Nonfarm

In [50]:
# Drop unnecessary columns
blsemp_df = blsemp_df.drop(columns=['Series ID','Period', 'Label'])

print('Unnecessary columns dropped successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_df.shape)
print(blsemp_df.info())

Unnecessary columns dropped successfully!
Data check:
Data shape: (3360, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3360 entries, 0 to 3359
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      3360 non-null   int64
 1   Value     3360 non-null   float64
 2   Industry  3360 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 78.9+ KB
None

In [51]:
# Remove Total Nonfarm row before calculating metrics
blsemp_df = blsemp_df[blsemp_df["Industry"] != "Total Nonfarm"]

print('Total Nonfarm row removed successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_df.shape)

Total Nonfarm row removed successfully!
Data check:
Data shape: (3120, 3)

In [52]:
# Change measure of values into correct format (1,000s of jobs)
blsemp_df['Value'] = blsemp_df['Value'] * 1000

# Round for readability
blsemp_df['Value'] = blsemp_df['Value'].round(2)

# Data check
print('Data check:')
blsemp_df.head()

Data check:

     Year    Value            Industry
240  2006  27200.0  Mining and Logging
241  2006  27400.0  Mining and Logging
242  2006  27700.0  Mining and Logging
243  2006  27800.0  Mining and Logging
244  2006  27900.0  Mining and Logging

In [53]:
# Create yearly employment averages by industry

blsemp_yearly = (
    blsemp_df
        .groupby(['Industry', 'Year'])['Value']
        .mean()
        .reset_index()
)

print('Yearly employment averages calculated successfully!')

# Round for readability
blsemp_yearly['Value'] = blsemp_yearly['Value'].round(1)

print('Values rounded successfully!')

# Rename for clarity
blsemp_yearly = blsemp_yearly.rename(columns={'Value': 'Employment'})

print('Values renamed successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
print(blsemp_yearly.info())
blsemp_yearly.head()

Yearly employment averages calculated successfully!
Values rounded successfully!
Values renamed successfully!
Data check:
Data shape: (260, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Industry    260 non-null    object
 1   Year        260 non-null    int64
 2   Employment  260 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.2+ KB
None

       Industry  Year  Employment
0  Construction  2006     39425.0
1  Construction  2007     38933.3
2  Construction  2008     38908.3
3  Construction  2009     34075.0
4  Construction  2010     32791.7

In [54]:
# Check for duplicates
duplicates = blsemp_yearly.duplicated().sum()
print('Number of duplicate rows:', duplicates)

# Check for missing values
print('Number of missing values:', blsemp_yearly.isna().sum())

# Sort by Industry and Year
blsemp_yearly = blsemp_yearly.sort_values(['Industry', 'Year'])

print('Data sorted successfully!')

Number of duplicate rows: 0
Number of missing values: Industry      0
Year          0
Employment    0
dtype: int64
Data sorted successfully!

In [55]:
# Calculate Year-over-Year percentage growth
blsemp_yearly['YoY_Growth'] = (
    blsemp_yearly
        .groupby('Industry')['Employment']
        .pct_change() * 100
)

# Round for readability
blsemp_yearly['YoY_Growth'] = blsemp_yearly['YoY_Growth'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

Values rounded successfully!
Data check:
Data shape: (260, 4)

       Industry  Year  Employment  YoY_Growth
0  Construction  2006     39425.0         NaN
1  Construction  2007     38933.3       -1.25
2  Construction  2008     38908.3       -0.06
3  Construction  2009     34075.0      -12.42
4  Construction  2010     32791.7       -3.77

In [56]:
# Calculate absolute yearly employment change
blsemp_yearly['Yearly_Change'] = (
    blsemp_yearly
        .groupby('Industry')['Employment']
        .diff()
)

print('Absolute yearly employment change calculated successfully!')

# Round for readability
blsemp_yearly['Yearly_Change'] = blsemp_yearly['Yearly_Change'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

Absolute yearly employment change calculated successfully!
Values rounded successfully!
Data check:
Data shape: (260, 5)

       Industry  Year  Employment  YoY_Growth  Yearly_Change
0  Construction  2006     39425.0         NaN            NaN
1  Construction  2007     38933.3       -1.25         -491.7
2  Construction  2008     38908.3       -0.06          -25.0
3  Construction  2009     34075.0      -12.42        -4833.3
4  Construction  2010     32791.7       -3.77        -1283.3

In [57]:
# Calculate total employment per year
blsemp_yearly['Total_Employment_Year'] = (
    blsemp_yearly
        .groupby('Year')['Employment']
        .transform('sum')
)

print('Total employment per year calculated successfully!')

# Calculate industry share of total employment
blsemp_yearly['Industry_Share_Pct'] = (
    blsemp_yearly['Employment'] /
    blsemp_yearly['Total_Employment_Year']
) * 100

print('Industry share of total employment calculated successfully!')

# Round for readability
blsemp_yearly['Total_Employment_Year'] = blsemp_yearly['Total_Employment_Year'].round(2)
blsemp_yearly['Industry_Share_Pct'] = blsemp_yearly['Industry_Share_Pct'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

Total employment per year calculated successfully!
Industry share of total employment calculated successfully!
Values rounded successfully!
Data check:
Data shape: (260, 7)

,Industry,Year,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct
0,Construction,2006,39425.0,NaN,NaN,722683.2,5.46
1,Construction,2007,38933.3,-1.25,-491.7,722891.5,5.39
2,Construction,2008,38908.3,-0.06,-25.0,727808.1,5.35
3,Construction,2009,34075.0,-12.42,-4833.3,710933.3,4.79
4,Construction,2010,32791.7,-3.77,-1283.3,712816.7,4.60

In [58]:
# Group by Year and calculate sum of Industry_Share_Pct

blsemp_yearly.groupby('Year')['Industry_Share_Pct'].sum().round(2).head(25)

print('Data grouped and summed successfully!')

Data grouped and summed successfully!

In [59]:
# Calculate 3-year rolling average of YoY growth
blsemp_yearly['YoY_Growth_3yr_Avg'] = (
    blsemp_yearly
        .groupby('Industry')['YoY_Growth']
        .rolling(window=3)
        .mean()
        .reset_index(level=0, drop=True)
)

print('3-year rolling average of YoY growth calculated successfully!')

# Round for readability
blsemp_yearly['YoY_Growth_3yr_Avg'] = blsemp_yearly['YoY_Growth_3yr_Avg'].round(2)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

3-year rolling average of YoY growth calculated successfully!
Values rounded successfully!
Data check:
Data shape: (260, 8)

,Industry,Year,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct,YoY_Growth_3yr_Avg
0,Construction,2006,39425.0,NaN,NaN,722683.2,5.46,NaN
1,Construction,2007,38933.3,-1.25,-491.7,722891.5,5.39,NaN
2,Construction,2008,38908.3,-0.06,-25.0,727808.1,5.35,NaN
3,Construction,2009,34075.0,-12.42,-4833.3,710933.3,4.79,-4.58
4,Construction,2010,32791.7,-3.77,-1283.3,712816.7,4.60,-5.42

In [60]:
# Rank industries by employment size within each year
blsemp_yearly['Industry_Rank'] = (
    blsemp_yearly
        .groupby('Year')['Employment']
        .rank(method='first', ascending=False)
)

print('Industries ranked successfully!')

# Change data type to integer
blsemp_yearly['Industry_Rank'] = blsemp_yearly['Industry_Rank'].astype(int)

print('Data type changed successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

Industries ranked successfully!
Data type changed successfully!
Data check:
Data shape: (260, 9)

,Industry,Year,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct,YoY_Growth_3yr_Avg,Industry_Rank
0,Construction,2006,39425.0,NaN,NaN,722683.2,5.46,NaN,7
1,Construction,2007,38933.3,-1.25,-491.7,722891.5,5.39,NaN,7
2,Construction,2008,38908.3,-0.06,-25.0,727808.1,5.35,NaN,7
3,Construction,2009,34075.0,-12.42,-4833.3,710933.3,4.79,-4.58,7
4,Construction,2010,32791.7,-3.77,-1283.3,712816.7,4.60,-5.42,7

In [61]:
# Sort dataframe by Year and Industry_Rank

blsemp_yearly.sort_values(['Year', 'Industry_Rank']).head(15)

print('Data sorted successfully!')

Data sorted successfully!

In [62]:
# Calculate top 3 industry share per year
top3_share = (
    blsemp_yearly.loc[blsemp_yearly['Industry_Rank'] <= 3]
        .groupby('Year')['Industry_Share_Pct']
        .sum()
)

print('Top 3 industry share calculated successfully!')

# Assign to all rows in the dataframe per year
blsemp_yearly['Top3_Share_Pct'] = blsemp_yearly['Year'].map(top3_share)

print('Top 3 industry share assigned successfully!')

# Round for readability
blsemp_yearly['Top3_Share_Pct'] = blsemp_yearly['Top3_Share_Pct'].round(1)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

Top 3 industry share calculated successfully!
Top 3 industry share assigned successfully!
Values rounded successfully!
Data check:
Data shape: (260, 10)

,Industry,Year,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct,YoY_Growth_3yr_Avg,Industry_Rank,Top3_Share_Pct
0,Construction,2006,39425.0,NaN,NaN,722683.2,5.46,NaN,7,54.0
1,Construction,2007,38933.3,-1.25,-491.7,722891.5,5.39,NaN,7,54.1
2,Construction,2008,38908.3,-0.06,-25.0,727808.1,5.35,NaN,7,54.4
3,Construction,2009,34075.0,-12.42,-4833.3,710933.3,4.79,-4.58,7,55.6
4,Construction,2010,32791.7,-3.77,-1283.3,712816.7,4.60,-5.42,7,56.0

In [63]:
# Calculate HHI in 0-10000 scale
blsemp_yearly['HHI'] = (
    blsemp_yearly.groupby('Year')['Industry_Share_Pct']
        .transform(lambda x: (x**2).sum())
)

print('HHI calculated successfully!')

# Round for readability
blsemp_yearly['HHI'] = blsemp_yearly['HHI'].round(1)

print('Values rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_yearly.shape)
blsemp_yearly.head()

HHI calculated successfully!
Values rounded successfully!
Data check:
Data shape: (260, 11)

,Industry,Year,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct,YoY_Growth_3yr_Avg,Industry_Rank,Top3_Share_Pct,HHI
0,Construction,2006,39425.0,NaN,NaN,722683.2,5.46,NaN,7,54.0,1299.3
1,Construction,2007,38933.3,-1.25,-491.7,722891.5,5.39,NaN,7,54.1,1302.3
2,Construction,2008,38908.3,-0.06,-25.0,727808.1,5.35,NaN,7,54.4,1306.5
3,Construction,2009,34075.0,-12.42,-4833.3,710933.3,4.79,-4.58,7,55.6,1335.8
4,Construction,2010,32791.7,-3.77,-1283.3,712816.7,4.60,-5.42,7,56.0,1348.9

In [64]:
# Reorder columns
blsemp_yearly = blsemp_yearly[
    [
        'Year',
        'Industry',
        'Employment',
        'YoY_Growth',
        'Yearly_Change',
        'Total_Employment_Year',
        'Industry_Share_Pct',
        'YoY_Growth_3yr_Avg',
        'Top3_Share_Pct',
        'HHI',
        'Industry_Rank'
    ]
]

print('Columns reordered successfully!')    


# Sort columns by  

# Reset index
blsemp_clean = blsemp_yearly.reset_index(drop=True)

print('Index reset successfully!')

# Data check
print('Data check:')
blsemp_clean.info()

Columns reordered successfully!
Index reset successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   260 non-null    int64
 1   Industry               260 non-null    object
 2   Employment             260 non-null    float64
 3   YoY_Growth             247 non-null    float64
 4   Yearly_Change          247 non-null    float64
 5   Total_Employment_Year  260 non-null    float64
 6   Industry_Share_Pct     260 non-null    float64
 7   YoY_Growth_3yr_Avg     221 non-null    float64
 8   Top3_Share_Pct         260 non-null    float64
 9   HHI                    260 non-null    float64
 10  Industry_Rank          260 non-null    int64
dtypes: float64(8), int64(2), object(1)
memory usage: 22.5+ KB

In [65]:
# Sort dataframe by Year and Industry
blsemp_clean = blsemp_clean.sort_values(['Year', 'Industry'])

print('Data sorted successfully!')

# Change Year column from int64 to datetime
blsemp_clean['Year'] = pd.to_datetime(blsemp_clean['Year'], format='%Y')

print('Data type changed successfully!')

# Reset index
blsemp_clean = blsemp_clean.reset_index(drop=True)

print('Index reset successfully!')

# Data check
print('Data check:')
print('Data shape:', blsemp_clean.shape)
print(blsemp_clean.info())
blsemp_clean.head()

Data sorted successfully!
Data type changed successfully!
Index reset successfully!
Data check:
Data shape: (260, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   260 non-null    datetime64[ns]
 1   Industry               260 non-null    object
 2   Employment             260 non-null    float64
 3   YoY_Growth             247 non-null    float64
 4   Yearly_Change          247 non-null    float64
 5   Total_Employment_Year  260 non-null    float64
 6   Industry_Share_Pct     260 non-null    float64
 7   YoY_Growth_3yr_Avg     221 non-null    float64
 8   Top3_Share_Pct         260 non-null    float64
 9   HHI                    260 non-null    float64
 10  Industry_Rank          260 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(1)
memory usage: 22.5+ KB
None

,Year,Industry,Employment,YoY_Growth,Yearly_Change,Total_Employment_Year,Industry_Share_Pct,YoY_Growth_3yr_Avg,Top3_Share_Pct,HHI,Industry_Rank
0,2006-01-01,Construction,39425.0,NaN,NaN,722683.2,5.46,NaN,54.0,1299.3,7
1,2006-01-01,Finance and Insurance,21250.0,NaN,NaN,722683.2,2.94,NaN,54.0,1299.3,10
2,2006-01-01,Government,145608.3,NaN,NaN,722683.2,20.15,NaN,54.0,1299.3,1
3,2006-01-01,Health Care and Social Assistance,102408.3,NaN,NaN,722683.2,14.17,NaN,54.0,1299.3,3
4,2006-01-01,Information,11508.3,NaN,NaN,722683.2,1.59,NaN,54.0,1299.3,11

In [66]:
# Save cleaned data
blsemp_clean.to_csv('../../../workspace/nf-insights-project/data_clean/bls_employ_clean.csv', index=False)

print('CSV saved successfully!')

CSV saved successfully!