WVSOS Business Registrations data cleaning and exploration.

In [85]:
# Import libraries
import pandas as pd

print('Libraries imported successfully!')

Libraries imported successfully!

In [86]:
# Read in wvsos business registration data
wvsos_df = pd.read_csv('../../../workspace/nf-insights-project/data_raw/WVSOS Business Registrations Complete Data -Needs Cleaning.csv', low_memory=False)

print('CSV read successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

CSV read successfully!
Data check:
DF shape: (612365, 53)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612365 entries, 0 to 612364
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              612365 non-null  object
 1   Organization Name                                598092 non-null  object
 2   Org Type                                         598093 non-null  object
 3   Effective Date                                   598093 non-null  object
 4   Established Date                                 1547 non-null    object
 5   Filing Date                                      493214 non-null  object
 6   Charter                                          595125 non-null  object
 7   Class                                            495887 non-null  object
 8   Termination Date                                 321935 non-null  object
 9   Termination Reason                               318158 non-null  object
 10  Sec Type                                         1864 non-null    object
 11  Business Purpose                                 226180 non-null  object
 12  NAICS                                            226180 non-null  float64
 13  Charter County                                   281142 non-null  object
 14  Charter State                                    596301 non-null  object
 15  At Will Term                                     216826 non-null  object
 16  At Will Term Years                               109656 non-null  float64
 17  Authorized Shares                                207614 non-null  float64
 18  Capital Stock                                    200682 non-null  float64
 19  Control Number                                   371215 non-null  object
 20  Excess Acres                                     177457 non-null  float64
 21  Member Managed                                   215872 non-null  object
 22  Par Value                                        200669 non-null  float64
 23  Young Entrepreneur                               598093 non-null  object
 24  Addresses Type                                   594557 non-null  object
 25  Addresses Address                                594577 non-null  object
 26  Officers Type                                    566392 non-null  object
 27  Officers Name/Address                            566782 non-null  object
 28  DBA Name                                         132279 non-null  object
 29  DBA Description                                  132246 non-null  object
 30  DBA Effective Date                               132281 non-null  object
 31  DBA Termination Date                             77423 non-null   object
 32  Amendments                                       75425 non-null   object
 33  Amendment Date                                   75425 non-null   object
 34  Mergers Merged                                   4007 non-null    object
 35  Mergers Merged State                             3920 non-null    object
 36  Mergers Merger Date                              4007 non-null    object
 37  Mergers Survived                                 4007 non-null    object
 38  Mergers Survived State                           3944 non-null    object
 39  Dissolutions Action Pending                      5346 non-null    object
 40  Dissolutions Approval Request Date               4081 non-null    object
 41  Dissolutions Articles Date                       3566 non-null    object
 42  Dissolutions Employment Security Approval Date   5124 non-null    object
 43  Dissolutions Tax Approval Date                   4083 non-null    object
 44  Dissolutions Workers Compensation Approval Date  5188 non-null    object
 45  Subsidiaries Address                             3820 non-null    object
 46  Subsidiaries Name                                955 non-null     object
 47  Last Annual Report                               304790 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  136 non-null     object
 50  Education Status                                 358 non-null     object
 51  Field                                            155 non-null     object
 52  School                                           190 non-null     object
dtypes: float64(7), object(46)
memory usage: 247.6+ MB
None

,URL,Organization Name,Org Type,Effective Date,Established Date,Filing Date,Charter,Class,Termination Date,Termination Reason,...,Dissolutions Tax Approval Date,Dissolutions Workers Compensation Approval Date,Subsidiaries Address,Subsidiaries Name,Last Annual Report,Unnamed: 48,Education Level,Education Status,Field,School
0,https://apps.sos.wv.gov/business/corporations/...,#29 TRUCKING CO. INC.,C | Corporation,4/19/1985,NaN,4/19/1985,Domestic,Profit,9/11/1986,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,NaN
1,https://apps.sos.wv.gov/business/corporations/...,"A & C CABLE, INC.",C | Corporation,2/1/1984,NaN,2/1/1984,Domestic,Profit,5/5/1989,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://apps.sos.wv.gov/business/corporations/...,"A & C CONSTRUCTION CO., INC.",C | Corporation,9/14/1966,NaN,9/14/1966,Foreign,Profit,7/6/2007,Withdrawal (Foreign),...,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN
3,https://apps.sos.wv.gov/business/corporations/...,"A & C REALTY COMPANY, INC.",C | Corporation,3/29/1966,NaN,3/29/1966,Domestic,Profit,9/11/1986,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://apps.sos.wv.gov/business/corporations/...,"A & C TRANSPORT, INC.",C | Corporation,11/9/1984,NaN,11/9/1984,Foreign,Profit,4/25/1991,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,1990,NaN,NaN,NaN,NaN,NaN

In [87]:
# Convert date columns to datetime
date_columns = [
    'Filing Date',
    'Termination Date'
]

wvsos_df[date_columns] = wvsos_df[date_columns].apply(
    pd.to_datetime,
    errors='coerce'
)

print('Date columns converted successfully!')

# Convert NAICS to numeric
wvsos_df['NAICS'] = wvsos_df['NAICS'].astype('Int64')

print('NAICS converted to numeric successfully!')

# Data check
print('Data check:')
wvsos_df.info()

Date columns converted successfully!
NAICS converted to numeric successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612365 entries, 0 to 612364
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              612365 non-null  object
 1   Organization Name                                598092 non-null  object
 2   Org Type                                         598093 non-null  object
 3   Effective Date                                   598093 non-null  object
 4   Established Date                                 1547 non-null    object
 5   Filing Date                                      493211 non-null  datetime64[ns]
 6   Charter                                          595125 non-null  object
 7   Class                                            495887 non-null  object
 8   Termination Date                                 321935 non-null  datetime64[ns]
 9   Termination Reason                               318158 non-null  object
 10  Sec Type                                         1864 non-null    object
 11  Business Purpose                                 226180 non-null  object
 12  NAICS                                            226180 non-null  Int64
 13  Charter County                                   281142 non-null  object
 14  Charter State                                    596301 non-null  object
 15  At Will Term                                     216826 non-null  object
 16  At Will Term Years                               109656 non-null  float64
 17  Authorized Shares                                207614 non-null  float64
 18  Capital Stock                                    200682 non-null  float64
 19  Control Number                                   371215 non-null  object
 20  Excess Acres                                     177457 non-null  float64
 21  Member Managed                                   215872 non-null  object
 22  Par Value                                        200669 non-null  float64
 23  Young Entrepreneur                               598093 non-null  object
 24  Addresses Type                                   594557 non-null  object
 25  Addresses Address                                594577 non-null  object
 26  Officers Type                                    566392 non-null  object
 27  Officers Name/Address                            566782 non-null  object
 28  DBA Name                                         132279 non-null  object
 29  DBA Description                                  132246 non-null  object
 30  DBA Effective Date                               132281 non-null  object
 31  DBA Termination Date                             77423 non-null   object
 32  Amendments                                       75425 non-null   object
 33  Amendment Date                                   75425 non-null   object
 34  Mergers Merged                                   4007 non-null    object
 35  Mergers Merged State                             3920 non-null    object
 36  Mergers Merger Date                              4007 non-null    object
 37  Mergers Survived                                 4007 non-null    object
 38  Mergers Survived State                           3944 non-null    object
 39  Dissolutions Action Pending                      5346 non-null    object
 40  Dissolutions Approval Request Date               4081 non-null    object
 41  Dissolutions Articles Date                       3566 non-null    object
 42  Dissolutions Employment Security Approval Date   5124 non-null    object
 43  Dissolutions Tax Approval Date                   4083 non-null    object
 44  Dissolutions Workers Compensation Approval Date  5188 non-null    object
 45  Subsidiaries Address                             3820 non-null    object
 46  Subsidiaries Name                                955 non-null     object
 47  Last Annual Report                               304790 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  136 non-null     object
 50  Education Status                                 358 non-null     object
 51  Field                                            155 non-null     object
 52  School                                           190 non-null     object
dtypes: Int64(1), datetime64[ns](2), float64(6), object(44)
memory usage: 248.2+ MB

In [88]:
# Filter for years 2008-2025
wvsos_df = wvsos_df[
    (wvsos_df['Filing Date'] >= '2008-01-01') &
    (wvsos_df['Filing Date'] <= '2025-12-31')
]

print('Data filtered for years 2008-2025 successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
wvsos_df.info()

Data filtered for years 2008-2025 successfully!
Data check:
DF shape: (237957, 53)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              237957 non-null  object
 1   Organization Name                                237957 non-null  object
 2   Org Type                                         237957 non-null  object
 3   Effective Date                                   237957 non-null  object
 4   Established Date                                 1538 non-null    object
 5   Filing Date                                      237957 non-null  datetime64[ns]
 6   Charter                                          237498 non-null  object
 7   Class                                            236811 non-null  object
 8   Termination Date                                 95164 non-null   datetime64[ns]
 9   Termination Reason                               93271 non-null   object
 10  Sec Type                                         377 non-null     object
 11  Business Purpose                                 165436 non-null  object
 12  NAICS                                            165436 non-null  Int64
 13  Charter County                                   165278 non-null  object
 14  Charter State                                    237729 non-null  object
 15  At Will Term                                     172609 non-null  object
 16  At Will Term Years                               2812 non-null    float64
 17  Authorized Shares                                17804 non-null   float64
 18  Capital Stock                                    14318 non-null   float64
 19  Control Number                                   114628 non-null  object
 20  Excess Acres                                     339 non-null     float64
 21  Member Managed                                   172470 non-null  object
 22  Par Value                                        14326 non-null   float64
 23  Young Entrepreneur                               237957 non-null  object
 24  Addresses Type                                   237520 non-null  object
 25  Addresses Address                                237529 non-null  object
 26  Officers Type                                    234247 non-null  object
 27  Officers Name/Address                            234487 non-null  object
 28  DBA Name                                         39953 non-null   object
 29  DBA Description                                  39944 non-null   object
 30  DBA Effective Date                               39955 non-null   object
 31  DBA Termination Date                             10309 non-null   object
 32  Amendments                                       13322 non-null   object
 33  Amendment Date                                   13322 non-null   object
 34  Mergers Merged                                   1431 non-null    object
 35  Mergers Merged State                             1420 non-null    object
 36  Mergers Merger Date                              1431 non-null    object
 37  Mergers Survived                                 1431 non-null    object
 38  Mergers Survived State                           1430 non-null    object
 39  Dissolutions Action Pending                      2180 non-null    object
 40  Dissolutions Approval Request Date               2024 non-null    object
 41  Dissolutions Articles Date                       1687 non-null    object
 42  Dissolutions Employment Security Approval Date   1822 non-null    object
 43  Dissolutions Tax Approval Date                   1415 non-null    object
 44  Dissolutions Workers Compensation Approval Date  1978 non-null    object
 45  Subsidiaries Address                             555 non-null     object
 46  Subsidiaries Name                                133 non-null     object
 47  Last Annual Report                               158860 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  134 non-null     object
 50  Education Status                                 352 non-null     object
 51  Field                                            154 non-null     object
 52  School                                           188 non-null     object
dtypes: Int64(1), datetime64[ns](2), float64(6), object(44)
memory usage: 98.3+ MB

In [89]:
# Drop unneeded columns
wvsos_df = wvsos_df.drop(columns=[
    'URL',
    'Effective Date',
    'Established Date',
    'Charter',
    'Class',
    'Termination Reason',
    'Sec Type', 
    'Charter County',
    'At Will Term',
    'At Will Term Years',
    'Authorized Shares',
    'Capital Stock',
    'Control Number',
    'Excess Acres',
    'Member Managed',
    'Par Value',
    'Young Entrepreneur',  
    'Addresses Type',
    'Addresses Address',
    'Officers Type',
    'Officers Name/Address',
    'DBA Name',
    'DBA Description',
    'DBA Effective Date',
    'DBA Termination Date',
    'Amendments',
    'Amendment Date',
    'Mergers Merged',
    'Mergers Merged State',
    'Mergers Merger Date',
    'Mergers Survived',
    'Mergers Survived State',
    'Dissolutions Action Pending',
    'Dissolutions Approval Request Date',
    'Dissolutions Articles Date',
    'Dissolutions Employment Security Approval Date',
    'Dissolutions Tax Approval Date',
    'Dissolutions Workers Compensation Approval Date',
    'Subsidiaries Address',
    'Subsidiaries Name',
    'Last Annual Report',
    'Unnamed: 48',
    'Education Level',
    'Education Status',
    'Field',
    'School'
])

print('Unneeded columns dropped successfully!')        

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.info()

Unneeded columns dropped successfully!
Data check:
Data shape: (237957, 7)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
dtypes: Int64(1), datetime64[ns](2), object(4)
memory usage: 14.8+ MB

In [90]:
# Check for duplicates
print('Number of duplicates:', wvsos_df.duplicated().sum())

Number of duplicates: 13

In [91]:
# View the duplicate rows
duplicates = wvsos_df[wvsos_df.duplicated()]

print('Duplicate rows pulled successfully!')

# View the duplicate rows
print('Duplicate rows:')
duplicates.head()

Duplicate rows pulled successfully!
Duplicate rows:

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State
321321,BAYPO II LLC,LLC | Limited Liability Company,2008-03-03,2013-07-02,NaN,<NA>,DE
484959,TENMILE LAND GRAPHIC SYMBOL AND WORDING,TMO | Trademark Holder,2019-11-19,2029-11-19,NaN,<NA>,WV
538029,395 WINSTON ROAD LLC,LLC | Limited Liability Company,2022-08-04,NaT,NaN,<NA>,VA
552618,KATHY'S CG SERVICE LLC,LLC | Limited Liability Company,2023-03-07,NaT,NaN,<NA>,WV
559189,GLENVILLE SNF OPERATIONS LLC,LLC | Limited Liability Company,2023-07-06,NaT,NaN,<NA>,NV

In [92]:
# Extract year from Filing Date
wvsos_df['Filing Year'] = wvsos_df['Filing Date'].dt.year.astype('Int64')
wvsos_df['Filing Month'] = wvsos_df['Filing Date'].dt.month.astype('Int64')

# Extract year from Termination Date
wvsos_df['Termination Year'] = wvsos_df['Termination Date'].dt.year.astype('Int64')
wvsos_df['Termination Month'] = wvsos_df['Termination Date'].dt.month.astype('Int64')

print('Year columns extracted successfully!')

# Data check
print('Data check:')
wvsos_df.info()

Year columns extracted successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Filing Month       237957 non-null  Int64
 9   Termination Year   95164 non-null   Int64
 10  Termination Month  95164 non-null   Int64
dtypes: Int64(5), datetime64[ns](2), object(4)
memory usage: 22.9+ MB

In [93]:
# Strip whitespace from all text columns
text_cols = wvsos_df.select_dtypes(include='object').columns

for col in text_cols:
    wvsos_df[col] = wvsos_df[col].str.strip()

print('Whitespace stripped successfully!')

Whitespace stripped successfully!

In [101]:
# Unique NAICS codes
print(sorted(wvsos_df["NAICS"].dropna().unique().tolist()))

print('Unique NAICS pulled successfully!')

[1111, 1112, 1113, 1114, 1119, 1121, 1122, 1123, 1124, 1125, 1129, 1131, 1132, 1133, 1141, 1142, 1151, 1152, 1153, 2111, 2121, 2122, 2123, 2131, 2211, 2212, 2213, 2361, 2362, 2371, 2372, 2373, 2379, 2381, 2382, 2383, 2389, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3121, 3122, 3131, 3132, 3133, 3141, 3149, 3151, 3152, 3159, 3161, 3162, 3169, 3211, 3212, 3219, 3221, 3222, 3231, 3241, 3251, 3252, 3253, 3254, 3255, 3256, 3259, 3261, 3262, 3271, 3272, 3273, 3274, 3279, 3311, 3312, 3313, 3314, 3315, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3331, 3332, 3333, 3334, 3335, 3336, 3339, 3341, 3342, 3343, 3344, 3345, 3346, 3351, 3352, 3353, 3359, 3361, 3362, 3363, 3364, 3365, 3366, 3369, 3371, 3372, 3379, 3391, 3399, 4231, 4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4251, 4411, 4412, 4413, 4421, 4422, 4431, 4441, 4442, 4451, 4452, 4453, 4461, 4471, 4481, 4482, 4483, 4511, 4512, 4521, 4529, 4531, 4532, 4533, 4539, 4541, 4542, 4543, 4811, 4812, 4821, 4831, 4832, 4841, 4842, 4851, 4852, 4853, 4854, 4855, 4859, 4861, 4862, 4869, 4871, 4872, 4879, 4881, 4882, 4883, 4884, 4885, 4889, 4911, 4921, 4922, 4931, 5111, 5112, 5121, 5122, 5151, 5152, 5171, 5172, 5174, 5179, 5182, 5191, 5211, 5222, 5223, 5231, 5232, 5239, 5241, 5242, 5251, 5259, 5311, 5312, 5313, 5321, 5322, 5323, 5324, 5331, 5411, 5412, 5413, 5414, 5415, 5416, 5417, 5418, 5419, 5511, 5611, 5612, 5613, 5614, 5615, 5616, 5617, 5619, 5621, 5622, 5629, 6111, 6112, 6113, 6114, 6115, 6116, 6117, 6211, 6212, 6213, 6214, 6215, 6216, 6219, 6221, 6222, 6223, 6231, 6232, 6233, 6239, 6241, 6242, 6243, 6244, 7111, 7112, 7113, 7114, 7115, 7121, 7131, 7132, 7139, 7211, 7212, 7213, 7223, 7224, 7225, 8111, 8112, 8113, 8114, 8121, 8122, 8123, 8129, 8131, 8132, 8133, 8134, 8139, 8141, 9211, 9221, 9231, 9241, 9251, 9261, 9271, 9281]
Unique NAICS pulled successfully!

In [102]:
# Create 2-digit NAICS sector
wvsos_df["NAICS_2"] = (
    wvsos_df["NAICS"]
    .astype("Int64")
    .astype(str)
    .str[:2]
)

print('2-digit NAICS created successfully!')

# Data check
print('Data check:')
wvsos_df.info()

2-digit NAICS created successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Filing Month       237957 non-null  Int64
 9   Termination Year   95164 non-null   Int64
 10  Termination Month  95164 non-null   Int64
 11  NAICS_2            237957 non-null  object
dtypes: Int64(5), datetime64[ns](2), object(5)
memory usage: 24.7+ MB

In [103]:
sorted(wvsos_df["NAICS_2"].dropna().unique())

['11',
 '21',
 '22',
 '23',
 '31',
 '32',
 '33',
 '42',
 '44',
 '45',
 '48',
 '49',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '61',
 '62',
 '71',
 '72',
 '81',
 '92',
 '<N']

In [ ]:
# Map WVSOS NAICS industries to BEA/BLS categories
def map_industry(sector):
    if sector in ["21", "11"]:
        return "Mining and Logging"
    elif sector == "23":
        return "Construction"
    elif sector in ["31", "32", "33"]:
        return "Manufacturing"
    elif sector in ["42", "44", "45", "48", "49", "22"]:
        return "Trade, Transportation, and Utilities"
    elif sector == "51":
        return "Information"
    elif sector == "52":
        return "Finance and Insurance"
    elif sector == "53":
        return "Real Estate and Rental and Leasing"
    elif sector in ["54", "55", "56"]:
        return "Professional and Business Services"
    elif sector == "61":
        return "Private Education Services"
    elif sector == "62":
        return "Health Care and Social Assistance"
    elif sector in ["71", "72"]:
        return "Leisure and Hospitality"
    elif sector == "81":
        return "Other Services"
    elif sector == "92":
        return "Government"
    else:
        return "Unmapped"

wvsos_df["IndustryMapped"] = wvsos_df["NAICS_2"].apply(map_industry)

print('NAICS mapped successfully!')

# Data check
print('Data check:')
print(wvsos_df.info())
wvsos_df.head()

NAICS mapped successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Filing Month       237957 non-null  Int64
 9   Termination Year   95164 non-null   Int64
 10  Termination Month  95164 non-null   Int64
 11  NAICS_2            237957 non-null  object
 12  IndustryMapped     237957 non-null  object
dtypes: Int64(5), datetime64[ns](2), object(6)
memory usage: 26.6+ MB
None

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State,Filing Year,Filing Month,Termination Year,Termination Month,NAICS_2,IndustryMapped
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019-02-26,NaT,Health Care and Social Assistance - Ambulatory...,6214,WV,2019,2,<NA>,<NA>,62,Health Care and Social Assistance
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013-08-15,2015-07-30,NaN,<NA>,WV,2013,8,2015,7,<N,Unmapped
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015-08-19,NaT,Health Care and Social Assistance - Ambulatory...,6211,WV,2015,8,<NA>,<NA>,62,Health Care and Social Assistance
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018-06-18,NaT,"Retail Trade - Sporting Goods, Hobby, Book, an...",4511,WV,2018,6,<NA>,<NA>,45,"Trade, Transportation, and Utilities"
1777,"ROTHCO FORD, INC.",C | Corporation,2017-05-15,2018-06-21,Real Estate and Rental and Leasing - Real Esta...,5311,WV,2017,5,2018,6,53,Real Estate and Rental and Leasing

In [106]:
print(wvsos_df["IndustryMapped"].value_counts())

IndustryMapped
Unmapped                                72521
Trade, Transportation, and Utilities    27608
Real Estate and Rental and Leasing      24649
Professional and Business Services      24105
Construction                            19900
Other Services                          19229
Leisure and Hospitality                 11231
Mining and Logging                       8881
Finance and Insurance                    7616
Manufacturing                            7344
Health Care and Social Assistance        6979
Information                              4022
Private Education Services               3326
Government                                546
Name: count, dtype: int64

In [113]:
print(
    wvsos_df.loc[
        wvsos_df["IndustryMapped"] == "Unmapped",
        ["NAICS", "Business Purpose"]
    ].head(20).to_string()
)

        NAICS Business Purpose
1128     <NA>              NaN
1943     <NA>              NaN
5039     <NA>              NaN
5389     <NA>              NaN
6002     <NA>              NaN
6889     <NA>              NaN
11776    <NA>              NaN
18335    <NA>              NaN
22738    <NA>              NaN
22747    <NA>              NaN
27175    <NA>              NaN
38594    <NA>              NaN
57651    <NA>              NaN
73522    <NA>              NaN
85081    <NA>              NaN
85660    <NA>              NaN
92661    <NA>              NaN
116936   <NA>              NaN
124501   <NA>              NaN
126728   <NA>              NaN

In [108]:
wvsos_df["NAICS"].isna().sum()

np.int64(72521)

In [ ]:
# # Mapping from WVSOS NAICS to BEA/BLS categories
# bea_mapping = {
#     'Health Care and Social Assistance': 'Health Care and Social Assistance',
#     'Retail Trade': 'Trade, Transportation, and Utilities',
#     'Wholesale Trade': 'Trade, Transportation, and Utilities',
#     'Mining, Quarrying, Oil & Gas Extraction': 'Mining and Logging',
#     'Construction': 'Construction',
#     'Real Estate and Rental and Leasing': 'Real Estate and Rental and Leasing',
#     'Other Services (except Public Administration)': 'Other Services',
#     'Finance and Insurance': 'Finance and Insurance',
#     'Accomodation and Food Services': 'Leisure and Hospitality',
#     'Manufacturing': 'Manufacturing',
#     'Agriculture, Forestry, Fishing and Hunting': 'Mining and Logging',
#     'Management of Companies and Enterprises': 'Professional and Business Services',
#     'Public Administration': 'Government',
#     'Educational Services': 'Private Education Services',
#     'Arts, Entertainment, and Recreation': 'Leisure and Hospitality',
#     'Professional, Scientific and Techincal Servies': 'Professional and Business Services',
#     'Transportation and Warehousing': 'Trade, Transportation, and Utilities',
#     'Information': 'Information',
#     'Admin/Support Waste Mgt/Remediation Services': 'Professional and Business Services',
#     'Utilities': 'Trade, Transportation, and Utilities',
#     # Any missing or unmatched will default to 'Unmapped'
# }

# # Create a new column with the mapped industries
# wvsos_df['Industry'] = wvsos_df['Main Industry'].map(bea_mapping).fillna('Unmapped')

# print('Industries mapped successfully!')

# # Data check
# print('Data check:')
# print(wvsos_df.info())
# wvsos_df.head()

In [114]:
# Filter out TMO (trademark holder) registrations before metric calculations
wvsos_df = wvsos_df[wvsos_df['Org Type'] != 'TMO | Trademark Holder']

print('TMO (trademark holder) registrations removed successfully!')

TMO (trademark holder) registrations removed successfully!

In [ ]:
# Count new registrations by year
registrations_per_year = wvsos_df.groupby('Filing Year').size().to_dict()

# Add a new column to wvsos_df with yearly registrations
wvsos_df['Yearly_Registrations'] = wvsos_df['Filing Year'].map(registrations_per_year)

print('Yearly registrations added successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

Yearly registrations added successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 237549 entries, 773 to 612360
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Organization Name     237549 non-null  object
 1   Org Type              237549 non-null  object
 2   Filing Date           237549 non-null  datetime64[ns]
 3   Termination Date      94764 non-null   datetime64[ns]
 4   Business Purpose      165435 non-null  object
 5   NAICS                 165435 non-null  Int64
 6   Charter State         237447 non-null  object
 7   Filing Year           237549 non-null  Int64
 8   Filing Month          237549 non-null  Int64
 9   Termination Year      94764 non-null   Int64
 10  Termination Month     94764 non-null   Int64
 11  NAICS_2               237549 non-null  object
 12  IndustryMapped        237549 non-null  object
 13  Yearly_Registrations  237549 non-null  int64
dtypes: Int64(5), datetime64[ns](2), int64(1), object(6)
memory usage: 28.3+ MB
None

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State,Filing Year,Filing Month,Termination Year,Termination Month,NAICS_2,IndustryMapped,Yearly_Registrations
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019-02-26,NaT,Health Care and Social Assistance - Ambulatory...,6214,WV,2019,2,<NA>,<NA>,62,Health Care and Social Assistance,13194
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013-08-15,2015-07-30,NaN,<NA>,WV,2013,8,2015,7,<N,Unmapped,11356
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015-08-19,NaT,Health Care and Social Assistance - Ambulatory...,6211,WV,2015,8,<NA>,<NA>,62,Health Care and Social Assistance,11404
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018-06-18,NaT,"Retail Trade - Sporting Goods, Hobby, Book, an...",4511,WV,2018,6,<NA>,<NA>,45,"Trade, Transportation, and Utilities",12981
1777,"ROTHCO FORD, INC.",C | Corporation,2017-05-15,2018-06-21,Real Estate and Rental and Leasing - Real Esta...,5311,WV,2017,5,2018,6,53,Real Estate and Rental and Leasing,11966

In [117]:
# Count terminated businesses by year
closures_per_year = wvsos_df.groupby('Termination Year').size().to_dict()

# Add a new column to wvsos_df with yearly closures
wvsos_df['Yearly_Closures'] = wvsos_df['Termination Year'].map(closures_per_year)

print('Yearly closures added successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

Yearly closures added successfully!
Data check:
Data shape: (237549, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 237549 entries, 773 to 612360
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Organization Name     237549 non-null  object
 1   Org Type              237549 non-null  object
 2   Filing Date           237549 non-null  datetime64[ns]
 3   Termination Date      94764 non-null   datetime64[ns]
 4   Business Purpose      165435 non-null  object
 5   NAICS                 165435 non-null  Int64
 6   Charter State         237447 non-null  object
 7   Filing Year           237549 non-null  Int64
 8   Filing Month          237549 non-null  Int64
 9   Termination Year      94764 non-null   Int64
 10  Termination Month     94764 non-null   Int64
 11  NAICS_2               237549 non-null  object
 12  IndustryMapped        237549 non-null  object
 13  Yearly_Registrations  237549 non-null  int64
 14  Yearly_Closures       94764 non-null   float64
dtypes: Int64(5), datetime64[ns](2), float64(1), int64(1), object(6)
memory usage: 30.1+ MB
None

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State,Filing Year,Filing Month,Termination Year,Termination Month,NAICS_2,IndustryMapped,Yearly_Registrations,Yearly_Closures
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019-02-26,NaT,Health Care and Social Assistance - Ambulatory...,6214,WV,2019,2,<NA>,<NA>,62,Health Care and Social Assistance,13194,NaN
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013-08-15,2015-07-30,NaN,<NA>,WV,2013,8,2015,7,<N,Unmapped,11356,7252.0
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015-08-19,NaT,Health Care and Social Assistance - Ambulatory...,6211,WV,2015,8,<NA>,<NA>,62,Health Care and Social Assistance,11404,NaN
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018-06-18,NaT,"Retail Trade - Sporting Goods, Hobby, Book, an...",4511,WV,2018,6,<NA>,<NA>,45,"Trade, Transportation, and Utilities",12981,NaN
1777,"ROTHCO FORD, INC.",C | Corporation,2017-05-15,2018-06-21,Real Estate and Rental and Leasing - Real Esta...,5311,WV,2017,5,2018,6,53,Real Estate and Rental and Leasing,11966,2753.0

In [ ]:
# # Reset index
# wvsos_clean = wvsos_df.reset_index(drop=True)

# print('Index reset successfully!')

# # Save cleaned data
# wvsos_clean.to_csv('../../../workspace/nf-insights-project/data_clean/wvsos_business_registrations_clean.csv', index=False)

# print('CSV saved successfully!')