WVSOS Business Registrations data cleaning and exploration.

In [328]:
# Import libraries
import pandas as pd

print('Libraries imported successfully!')

Libraries imported successfully!

In [329]:
# Read in wvsos business registration data
wvsos_df = pd.read_csv('../../../workspace/nf-insights-project/data_raw/WVSOS Business Registrations Complete Data -Needs Cleaning.csv', low_memory=False)

print('CSV read successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

CSV read successfully!
Data check:
DF shape: (612365, 53)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612365 entries, 0 to 612364
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              612365 non-null  object
 1   Organization Name                                598092 non-null  object
 2   Org Type                                         598093 non-null  object
 3   Effective Date                                   598093 non-null  object
 4   Established Date                                 1547 non-null    object
 5   Filing Date                                      493214 non-null  object
 6   Charter                                          595125 non-null  object
 7   Class                                            495887 non-null  object
 8   Termination Date                                 321935 non-null  object
 9   Termination Reason                               318158 non-null  object
 10  Sec Type                                         1864 non-null    object
 11  Business Purpose                                 226180 non-null  object
 12  NAICS                                            226180 non-null  float64
 13  Charter County                                   281142 non-null  object
 14  Charter State                                    596301 non-null  object
 15  At Will Term                                     216826 non-null  object
 16  At Will Term Years                               109656 non-null  float64
 17  Authorized Shares                                207614 non-null  float64
 18  Capital Stock                                    200682 non-null  float64
 19  Control Number                                   371215 non-null  object
 20  Excess Acres                                     177457 non-null  float64
 21  Member Managed                                   215872 non-null  object
 22  Par Value                                        200669 non-null  float64
 23  Young Entrepreneur                               598093 non-null  object
 24  Addresses Type                                   594557 non-null  object
 25  Addresses Address                                594577 non-null  object
 26  Officers Type                                    566392 non-null  object
 27  Officers Name/Address                            566782 non-null  object
 28  DBA Name                                         132279 non-null  object
 29  DBA Description                                  132246 non-null  object
 30  DBA Effective Date                               132281 non-null  object
 31  DBA Termination Date                             77423 non-null   object
 32  Amendments                                       75425 non-null   object
 33  Amendment Date                                   75425 non-null   object
 34  Mergers Merged                                   4007 non-null    object
 35  Mergers Merged State                             3920 non-null    object
 36  Mergers Merger Date                              4007 non-null    object
 37  Mergers Survived                                 4007 non-null    object
 38  Mergers Survived State                           3944 non-null    object
 39  Dissolutions Action Pending                      5346 non-null    object
 40  Dissolutions Approval Request Date               4081 non-null    object
 41  Dissolutions Articles Date                       3566 non-null    object
 42  Dissolutions Employment Security Approval Date   5124 non-null    object
 43  Dissolutions Tax Approval Date                   4083 non-null    object
 44  Dissolutions Workers Compensation Approval Date  5188 non-null    object
 45  Subsidiaries Address                             3820 non-null    object
 46  Subsidiaries Name                                955 non-null     object
 47  Last Annual Report                               304790 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  136 non-null     object
 50  Education Status                                 358 non-null     object
 51  Field                                            155 non-null     object
 52  School                                           190 non-null     object
dtypes: float64(7), object(46)
memory usage: 247.6+ MB
None

,URL,Organization Name,Org Type,Effective Date,Established Date,Filing Date,Charter,Class,Termination Date,Termination Reason,...,Dissolutions Tax Approval Date,Dissolutions Workers Compensation Approval Date,Subsidiaries Address,Subsidiaries Name,Last Annual Report,Unnamed: 48,Education Level,Education Status,Field,School
0,https://apps.sos.wv.gov/business/corporations/...,#29 TRUCKING CO. INC.,C | Corporation,4/19/1985,NaN,4/19/1985,Domestic,Profit,9/11/1986,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,NaN
1,https://apps.sos.wv.gov/business/corporations/...,"A & C CABLE, INC.",C | Corporation,2/1/1984,NaN,2/1/1984,Domestic,Profit,5/5/1989,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://apps.sos.wv.gov/business/corporations/...,"A & C CONSTRUCTION CO., INC.",C | Corporation,9/14/1966,NaN,9/14/1966,Foreign,Profit,7/6/2007,Withdrawal (Foreign),...,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN
3,https://apps.sos.wv.gov/business/corporations/...,"A & C REALTY COMPANY, INC.",C | Corporation,3/29/1966,NaN,3/29/1966,Domestic,Profit,9/11/1986,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://apps.sos.wv.gov/business/corporations/...,"A & C TRANSPORT, INC.",C | Corporation,11/9/1984,NaN,11/9/1984,Foreign,Profit,4/25/1991,Dissolution by Court Order,...,NaN,NaN,NaN,NaN,1990,NaN,NaN,NaN,NaN,NaN

In [330]:
# Convert date columns to datetime
date_columns = [
    'Filing Date',
    'Termination Date'
]

wvsos_df[date_columns] = wvsos_df[date_columns].apply(
    pd.to_datetime,
    errors='coerce'
)

print('Date columns converted successfully!')

# Convert NAICS to numeric
wvsos_df['NAICS'] = wvsos_df['NAICS'].astype('Int64')

print('NAICS converted to numeric successfully!')

# Data check
print('Data check:')
wvsos_df.info()

Date columns converted successfully!
NAICS converted to numeric successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612365 entries, 0 to 612364
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              612365 non-null  object
 1   Organization Name                                598092 non-null  object
 2   Org Type                                         598093 non-null  object
 3   Effective Date                                   598093 non-null  object
 4   Established Date                                 1547 non-null    object
 5   Filing Date                                      493211 non-null  datetime64[ns]
 6   Charter                                          595125 non-null  object
 7   Class                                            495887 non-null  object
 8   Termination Date                                 321935 non-null  datetime64[ns]
 9   Termination Reason                               318158 non-null  object
 10  Sec Type                                         1864 non-null    object
 11  Business Purpose                                 226180 non-null  object
 12  NAICS                                            226180 non-null  Int64
 13  Charter County                                   281142 non-null  object
 14  Charter State                                    596301 non-null  object
 15  At Will Term                                     216826 non-null  object
 16  At Will Term Years                               109656 non-null  float64
 17  Authorized Shares                                207614 non-null  float64
 18  Capital Stock                                    200682 non-null  float64
 19  Control Number                                   371215 non-null  object
 20  Excess Acres                                     177457 non-null  float64
 21  Member Managed                                   215872 non-null  object
 22  Par Value                                        200669 non-null  float64
 23  Young Entrepreneur                               598093 non-null  object
 24  Addresses Type                                   594557 non-null  object
 25  Addresses Address                                594577 non-null  object
 26  Officers Type                                    566392 non-null  object
 27  Officers Name/Address                            566782 non-null  object
 28  DBA Name                                         132279 non-null  object
 29  DBA Description                                  132246 non-null  object
 30  DBA Effective Date                               132281 non-null  object
 31  DBA Termination Date                             77423 non-null   object
 32  Amendments                                       75425 non-null   object
 33  Amendment Date                                   75425 non-null   object
 34  Mergers Merged                                   4007 non-null    object
 35  Mergers Merged State                             3920 non-null    object
 36  Mergers Merger Date                              4007 non-null    object
 37  Mergers Survived                                 4007 non-null    object
 38  Mergers Survived State                           3944 non-null    object
 39  Dissolutions Action Pending                      5346 non-null    object
 40  Dissolutions Approval Request Date               4081 non-null    object
 41  Dissolutions Articles Date                       3566 non-null    object
 42  Dissolutions Employment Security Approval Date   5124 non-null    object
 43  Dissolutions Tax Approval Date                   4083 non-null    object
 44  Dissolutions Workers Compensation Approval Date  5188 non-null    object
 45  Subsidiaries Address                             3820 non-null    object
 46  Subsidiaries Name                                955 non-null     object
 47  Last Annual Report                               304790 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  136 non-null     object
 50  Education Status                                 358 non-null     object
 51  Field                                            155 non-null     object
 52  School                                           190 non-null     object
dtypes: Int64(1), datetime64[ns](2), float64(6), object(44)
memory usage: 248.2+ MB

In [331]:
# Filter for years 2008-2025
wvsos_df = wvsos_df[
    (wvsos_df['Filing Date'] >= '2008-01-01') &
    (wvsos_df['Filing Date'] <= '2025-12-31')
]

print('Data filtered for years 2008-2025 successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
wvsos_df.info()

Data filtered for years 2008-2025 successfully!
Data check:
DF shape: (237957, 53)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 53 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   URL                                              237957 non-null  object
 1   Organization Name                                237957 non-null  object
 2   Org Type                                         237957 non-null  object
 3   Effective Date                                   237957 non-null  object
 4   Established Date                                 1538 non-null    object
 5   Filing Date                                      237957 non-null  datetime64[ns]
 6   Charter                                          237498 non-null  object
 7   Class                                            236811 non-null  object
 8   Termination Date                                 95164 non-null   datetime64[ns]
 9   Termination Reason                               93271 non-null   object
 10  Sec Type                                         377 non-null     object
 11  Business Purpose                                 165436 non-null  object
 12  NAICS                                            165436 non-null  Int64
 13  Charter County                                   165278 non-null  object
 14  Charter State                                    237729 non-null  object
 15  At Will Term                                     172609 non-null  object
 16  At Will Term Years                               2812 non-null    float64
 17  Authorized Shares                                17804 non-null   float64
 18  Capital Stock                                    14318 non-null   float64
 19  Control Number                                   114628 non-null  object
 20  Excess Acres                                     339 non-null     float64
 21  Member Managed                                   172470 non-null  object
 22  Par Value                                        14326 non-null   float64
 23  Young Entrepreneur                               237957 non-null  object
 24  Addresses Type                                   237520 non-null  object
 25  Addresses Address                                237529 non-null  object
 26  Officers Type                                    234247 non-null  object
 27  Officers Name/Address                            234487 non-null  object
 28  DBA Name                                         39953 non-null   object
 29  DBA Description                                  39944 non-null   object
 30  DBA Effective Date                               39955 non-null   object
 31  DBA Termination Date                             10309 non-null   object
 32  Amendments                                       13322 non-null   object
 33  Amendment Date                                   13322 non-null   object
 34  Mergers Merged                                   1431 non-null    object
 35  Mergers Merged State                             1420 non-null    object
 36  Mergers Merger Date                              1431 non-null    object
 37  Mergers Survived                                 1431 non-null    object
 38  Mergers Survived State                           1430 non-null    object
 39  Dissolutions Action Pending                      2180 non-null    object
 40  Dissolutions Approval Request Date               2024 non-null    object
 41  Dissolutions Articles Date                       1687 non-null    object
 42  Dissolutions Employment Security Approval Date   1822 non-null    object
 43  Dissolutions Tax Approval Date                   1415 non-null    object
 44  Dissolutions Workers Compensation Approval Date  1978 non-null    object
 45  Subsidiaries Address                             555 non-null     object
 46  Subsidiaries Name                                133 non-null     object
 47  Last Annual Report                               158860 non-null  object
 48  Unnamed: 48                                      0 non-null       float64
 49  Education Level                                  134 non-null     object
 50  Education Status                                 352 non-null     object
 51  Field                                            154 non-null     object
 52  School                                           188 non-null     object
dtypes: Int64(1), datetime64[ns](2), float64(6), object(44)
memory usage: 98.3+ MB

In [332]:
# Drop unneeded columns
wvsos_df = wvsos_df.drop(columns=[
    'URL',
    'Effective Date',
    'Established Date',
    'Charter',
    'Class',
    'Termination Reason',
    'Sec Type', 
    'Charter County',
    'At Will Term',
    'At Will Term Years',
    'Authorized Shares',
    'Capital Stock',
    'Control Number',
    'Excess Acres',
    'Member Managed',
    'Par Value',
    'Young Entrepreneur',  
    'Addresses Type',
    'Addresses Address',
    'Officers Type',
    'Officers Name/Address',
    'DBA Name',
    'DBA Description',
    'DBA Effective Date',
    'DBA Termination Date',
    'Amendments',
    'Amendment Date',
    'Mergers Merged',
    'Mergers Merged State',
    'Mergers Merger Date',
    'Mergers Survived',
    'Mergers Survived State',
    'Dissolutions Action Pending',
    'Dissolutions Approval Request Date',
    'Dissolutions Articles Date',
    'Dissolutions Employment Security Approval Date',
    'Dissolutions Tax Approval Date',
    'Dissolutions Workers Compensation Approval Date',
    'Subsidiaries Address',
    'Subsidiaries Name',
    'Last Annual Report',
    'Unnamed: 48',
    'Education Level',
    'Education Status',
    'Field',
    'School'
])

print('Unneeded columns dropped successfully!')        

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.info()

Unneeded columns dropped successfully!
Data check:
Data shape: (237957, 7)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
dtypes: Int64(1), datetime64[ns](2), object(4)
memory usage: 14.8+ MB

In [333]:
# Check for duplicates
print('Number of duplicates:', wvsos_df.duplicated().sum())

Number of duplicates: 13

In [334]:
# View the duplicate rows
duplicates = wvsos_df[wvsos_df.duplicated()]

print('Duplicate rows pulled successfully!')

# View the duplicate rows
print('Duplicate rows:')
duplicates.head()

Duplicate rows pulled successfully!
Duplicate rows:

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State
321321,BAYPO II LLC,LLC | Limited Liability Company,2008-03-03,2013-07-02,NaN,<NA>,DE
484959,TENMILE LAND GRAPHIC SYMBOL AND WORDING,TMO | Trademark Holder,2019-11-19,2029-11-19,NaN,<NA>,WV
538029,395 WINSTON ROAD LLC,LLC | Limited Liability Company,2022-08-04,NaT,NaN,<NA>,VA
552618,KATHY'S CG SERVICE LLC,LLC | Limited Liability Company,2023-03-07,NaT,NaN,<NA>,WV
559189,GLENVILLE SNF OPERATIONS LLC,LLC | Limited Liability Company,2023-07-06,NaT,NaN,<NA>,NV

In [335]:
# Extract year from Filing Date
wvsos_df['Filing Year'] = wvsos_df['Filing Date'].dt.year.astype('Int64')

# Extract year from Termination Date
wvsos_df['Termination Year'] = wvsos_df['Termination Date'].dt.year.astype('Int64')

print('Year columns extracted successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
wvsos_df.info()

Year columns extracted successfully!
Data check:
DF shape: (237957, 9)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Termination Year   95164 non-null   Int64
dtypes: Int64(3), datetime64[ns](2), object(4)
memory usage: 18.8+ MB

In [336]:
# Strip whitespace from all text columns
text_cols = wvsos_df.select_dtypes(include='object').columns

for col in text_cols:
    wvsos_df[col] = wvsos_df[col].str.strip()

print('Whitespace stripped successfully!')

Whitespace stripped successfully!

In [337]:
# Unique NAICS codes
print(sorted(wvsos_df['NAICS'].dropna().unique().tolist()))

print('Unique NAICS pulled successfully!')

[1111, 1112, 1113, 1114, 1119, 1121, 1122, 1123, 1124, 1125, 1129, 1131, 1132, 1133, 1141, 1142, 1151, 1152, 1153, 2111, 2121, 2122, 2123, 2131, 2211, 2212, 2213, 2361, 2362, 2371, 2372, 2373, 2379, 2381, 2382, 2383, 2389, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3121, 3122, 3131, 3132, 3133, 3141, 3149, 3151, 3152, 3159, 3161, 3162, 3169, 3211, 3212, 3219, 3221, 3222, 3231, 3241, 3251, 3252, 3253, 3254, 3255, 3256, 3259, 3261, 3262, 3271, 3272, 3273, 3274, 3279, 3311, 3312, 3313, 3314, 3315, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3331, 3332, 3333, 3334, 3335, 3336, 3339, 3341, 3342, 3343, 3344, 3345, 3346, 3351, 3352, 3353, 3359, 3361, 3362, 3363, 3364, 3365, 3366, 3369, 3371, 3372, 3379, 3391, 3399, 4231, 4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4251, 4411, 4412, 4413, 4421, 4422, 4431, 4441, 4442, 4451, 4452, 4453, 4461, 4471, 4481, 4482, 4483, 4511, 4512, 4521, 4529, 4531, 4532, 4533, 4539, 4541, 4542, 4543, 4811, 4812, 4821, 4831, 4832, 4841, 4842, 4851, 4852, 4853, 4854, 4855, 4859, 4861, 4862, 4869, 4871, 4872, 4879, 4881, 4882, 4883, 4884, 4885, 4889, 4911, 4921, 4922, 4931, 5111, 5112, 5121, 5122, 5151, 5152, 5171, 5172, 5174, 5179, 5182, 5191, 5211, 5222, 5223, 5231, 5232, 5239, 5241, 5242, 5251, 5259, 5311, 5312, 5313, 5321, 5322, 5323, 5324, 5331, 5411, 5412, 5413, 5414, 5415, 5416, 5417, 5418, 5419, 5511, 5611, 5612, 5613, 5614, 5615, 5616, 5617, 5619, 5621, 5622, 5629, 6111, 6112, 6113, 6114, 6115, 6116, 6117, 6211, 6212, 6213, 6214, 6215, 6216, 6219, 6221, 6222, 6223, 6231, 6232, 6233, 6239, 6241, 6242, 6243, 6244, 7111, 7112, 7113, 7114, 7115, 7121, 7131, 7132, 7139, 7211, 7212, 7213, 7223, 7224, 7225, 8111, 8112, 8113, 8114, 8121, 8122, 8123, 8129, 8131, 8132, 8133, 8134, 8139, 8141, 9211, 9221, 9231, 9241, 9251, 9261, 9271, 9281]
Unique NAICS pulled successfully!

In [338]:
# Create 2-digit NAICS sector for mapping to industry
wvsos_df['NAICS_2'] = (
    wvsos_df['NAICS']
    .astype('Int64')
    .astype(str)
    .str[:2]
)

print('2-digit NAICS created successfully!')

# Data check
print('Data check:')
wvsos_df.info()

2-digit NAICS created successfully!
Data check:
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Termination Year   95164 non-null   Int64
 9   NAICS_2            237957 non-null  object
dtypes: Int64(3), datetime64[ns](2), object(5)
memory usage: 20.7+ MB

In [339]:
# Pull unique NAICS_2 codes
print(sorted(wvsos_df['NAICS_2'].dropna().unique().tolist()))

print('Unique NAICS_2 pulled successfully!')

['11', '21', '22', '23', '31', '32', '33', '42', '44', '45', '48', '49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '<N']
Unique NAICS_2 pulled successfully!

In [340]:
# Map WVSOS NAICS industries to BEA/BLS categories
def map_industry(sector):
    if sector in ['21', '11']:
        return 'Mining and Logging'
    elif sector == '23':
        return 'Construction'
    elif sector in ['31', '32', '33']:
        return 'Manufacturing'
    elif sector in ['42', '44', '45', '48', '49', '22']:
        return 'Trade, Transportation, and Utilities'
    elif sector == '51':
        return 'Information'
    elif sector == '52':
        return 'Finance and Insurance'
    elif sector == '53':
        return 'Real Estate and Rental and Leasing'
    elif sector in ['54', '55', '56']:
        return 'Professional and Business Services'
    elif sector == '61':
        return 'Private Education Services'
    elif sector == '62':
        return 'Health Care and Social Assistance'
    elif sector in ['71', '72']:
        return 'Leisure and Hospitality'
    elif sector == '81':
        return 'Other Services'
    elif sector == '92':
        return 'Government'
    else:
        return 'Unmapped'

wvsos_df['Industry'] = wvsos_df['NAICS_2'].apply(map_industry)

print('NAICS mapped successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

NAICS mapped successfully!
Data check:
DF shape: (237957, 11)
<class 'pandas.core.frame.DataFrame'>
Index: 237957 entries, 773 to 612360
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237957 non-null  object
 1   Org Type           237957 non-null  object
 2   Filing Date        237957 non-null  datetime64[ns]
 3   Termination Date   95164 non-null   datetime64[ns]
 4   Business Purpose   165436 non-null  object
 5   NAICS              165436 non-null  Int64
 6   Charter State      237729 non-null  object
 7   Filing Year        237957 non-null  Int64
 8   Termination Year   95164 non-null   Int64
 9   NAICS_2            237957 non-null  object
 10  Industry           237957 non-null  object
dtypes: Int64(3), datetime64[ns](2), object(6)
memory usage: 22.5+ MB
None

,Organization Name,Org Type,Filing Date,Termination Date,Business Purpose,NAICS,Charter State,Filing Year,Termination Year,NAICS_2,Industry
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019-02-26,NaT,Health Care and Social Assistance - Ambulatory...,6214,WV,2019,<NA>,62,Health Care and Social Assistance
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013-08-15,2015-07-30,NaN,<NA>,WV,2013,2015,<N,Unmapped
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015-08-19,NaT,Health Care and Social Assistance - Ambulatory...,6211,WV,2015,<NA>,62,Health Care and Social Assistance
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018-06-18,NaT,"Retail Trade - Sporting Goods, Hobby, Book, an...",4511,WV,2018,<NA>,45,"Trade, Transportation, and Utilities"
1777,"ROTHCO FORD, INC.",C | Corporation,2017-05-15,2018-06-21,Real Estate and Rental and Leasing - Real Esta...,5311,WV,2017,2018,53,Real Estate and Rental and Leasing

In [341]:
# Filter out TMO (trademark holder) registrations before metric calculations
wvsos_df = wvsos_df[wvsos_df['Org Type'] != 'TMO | Trademark Holder']

print('TMO (trademark holder) registrations removed successfully!')

# Null termination dates after 2025
wvsos_df.loc[wvsos_df["Termination Year"] > 2025, "Termination Year"] = pd.NA

print('Nulled termination dates after 2025 successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
print(wvsos_df.info())

TMO (trademark holder) registrations removed successfully!
Nulled termination dates after 2025 successfully!
Data check:
DF shape: (237549, 11)
<class 'pandas.core.frame.DataFrame'>
Index: 237549 entries, 773 to 612360
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237549 non-null  object
 1   Org Type           237549 non-null  object
 2   Filing Date        237549 non-null  datetime64[ns]
 3   Termination Date   94764 non-null   datetime64[ns]
 4   Business Purpose   165435 non-null  object
 5   NAICS              165435 non-null  Int64
 6   Charter State      237447 non-null  object
 7   Filing Year        237549 non-null  Int64
 8   Termination Year   93039 non-null   Int64
 9   NAICS_2            237549 non-null  object
 10  Industry           237549 non-null  object
dtypes: Int64(3), datetime64[ns](2), object(6)
memory usage: 22.4+ MB
None

In [342]:
# Remove more unneeded columns before starting metrics
wvsos_df = wvsos_df.drop(columns=['Filing Date', 'Termination Date', 'Business Purpose', 'NAICS', 'NAICS_2', 'Charter State'])

print('Unneeded columns removed successfully!')

# Data check
print('Data check:')
print('DF shape:', wvsos_df.shape)
print(wvsos_df.info())
wvsos_df.head()

Unneeded columns removed successfully!
Data check:
DF shape: (237549, 5)
<class 'pandas.core.frame.DataFrame'>
Index: 237549 entries, 773 to 612360
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Organization Name  237549 non-null  object
 1   Org Type           237549 non-null  object
 2   Filing Year        237549 non-null  Int64
 3   Termination Year   93039 non-null   Int64
 4   Industry           237549 non-null  object
dtypes: Int64(2), object(3)
memory usage: 11.3+ MB
None

,Organization Name,Org Type,Filing Year,Termination Year,Industry
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities"
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing

In [343]:
# Count new registrations by year and industry
registrations_per_year_industry = wvsos_df.groupby(['Filing Year', 'Industry']).size()

# Map counts back to wvsos_df
wvsos_df['Yearly Registrations'] = wvsos_df.set_index(['Filing Year', 'Industry']).index.map(registrations_per_year_industry)

print('Yearly registrations added successfully!')

# Fill nulls with 0 and convert to int
wvsos_df['Yearly Registrations'] = wvsos_df['Yearly Registrations'].fillna(0).astype(int)

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Yearly registrations added successfully!
Data check:
Data shape: (237549, 6)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316

In [344]:
# Count closures by year and industry
closures_per_year_industry = wvsos_df.groupby(['Termination Year', 'Industry']).size()

# Map counts back to wvsos_df
wvsos_df['Yearly Closures'] = wvsos_df.set_index(['Termination Year', 'Industry']).index.map(closures_per_year_industry)

print('Yearly closures added successfully!')

# Fill nulls with 0 and convert to int
wvsos_df['Yearly Closures'] = wvsos_df['Yearly Closures'].fillna(0).astype(int)

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Yearly closures added successfully!
Data check:
Data shape: (237549, 7)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291

In [345]:
# Calculate net business changes by year
wvsos_df['Net Business Change'] = wvsos_df['Yearly Registrations'] - wvsos_df['Yearly Closures']

print('Net business change added successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Net business change added successfully!
Data check:
Data shape: (237549, 8)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures,Net Business Change
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0,418
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596,-1307
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0,370
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0,1595
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291,1025

In [346]:
# Groupby total registrations per year
total_registrations_per_year = wvsos_df.groupby('Filing Year').size().to_dict()

# Total registrations per year and industry
registrations_per_year_industry = wvsos_df.groupby(['Filing Year', 'Industry']).size().to_dict()

# Calculate registration share at industry-year level
def compute_share(row):
    key = (row['Filing Year'], row['Industry'])
    industry_total = registrations_per_year_industry.get(key, 0)
    year_total = total_registrations_per_year.get(row['Filing Year'], 1)
    return industry_total / year_total

wvsos_df['Registration Share'] = wvsos_df.apply(compute_share, axis=1)

print('Registration industry share added successfully!')

# Round for readability
wvsos_df['Registration Share'] = wvsos_df['Registration Share'].round(2)

print('Registration industry share rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Registration industry share added successfully!
Registration industry share rounded successfully!
Data check:
Data shape: (237549, 9)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures,Net Business Change,Registration Share
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0,418,0.03
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596,-1307,0.29
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0,370,0.03
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0,1595,0.12
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291,1025,0.11

In [347]:
# Calculate HHI in 0-10000 scale
hhi_per_year = (
    wvsos_df[['Filing Year', 'Industry', 'Registration Share']]
    .drop_duplicates()
    .groupby('Filing Year')['Registration Share']
    .apply(lambda x: (x**2).sum() * 10000)
)

wvsos_df['HHI Business Formation'] = wvsos_df['Filing Year'].map(hhi_per_year)

print('HHI added successfully!')

# Change dtype from float to int
wvsos_df['HHI Business Formation'] = wvsos_df['HHI Business Formation'].astype(int)

print('HHI dtype changed successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

HHI added successfully!
HHI dtype changed successfully!
Data check:
Data shape: (237549, 10)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures,Net Business Change,Registration Share,HHI Business Formation
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0,418,0.03,1154
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596,-1307,0.29,1381
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0,370,0.03,1245
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0,1595,0.12,1291
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291,1025,0.11,1196

In [348]:
# Calculate industry net growth per year
# Sum net change per industry-year
industry_year_sum = wvsos_df.groupby(['Filing Year', 'Industry'], as_index=False)['Net Business Change'].sum()

# Calculate total net change per year
total_per_year = industry_year_sum.groupby('Filing Year')['Net Business Change'].sum()

# Calculate share per industry-year
industry_year_sum['Net Growth Share'] = (
    industry_year_sum['Net Business Change'] / industry_year_sum['Filing Year'].map(total_per_year)
)

# Map the correct share back to every row in the original dataframe
wvsos_df['Net Growth Share'] = wvsos_df.set_index(['Filing Year','Industry']).index.map(
    dict(zip(
        zip(industry_year_sum['Filing Year'], industry_year_sum['Industry']),
        industry_year_sum['Net Growth Share']
    ))
)

print('Net business growth added successfully!')

# Round for readability
wvsos_df['Net Growth Share'] = wvsos_df['Net Growth Share'].round(2)

print('Net business growth rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Net business growth added successfully!
Net business growth rounded successfully!
Data check:
Data shape: (237549, 11)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures,Net Business Change,Registration Share,HHI Business Formation,Net Growth Share
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0,418,0.03,1154,0.01
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596,-1307,0.29,1381,0.05
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0,370,0.03,1245,0.01
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0,1595,0.12,1291,0.14
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291,1025,0.11,1196,0.16

In [349]:
# Calculate net business growth rate per year
# Sum net change per industry-year
industry_year_net = wvsos_df.groupby(['Filing Year','Industry'], as_index=False)['Net Business Change'].sum()

# Calculate pct_change per industry
industry_year_net['Net Growth Rate'] = industry_year_net.groupby('Industry')['Net Business Change'].pct_change() * 100

# Map back to every row in wvsos_df
wvsos_df['Net Growth Rate'] = wvsos_df.set_index(['Filing Year','Industry']).index.map(
    dict(zip(
        zip(industry_year_net['Filing Year'], industry_year_net['Industry']),
        industry_year_net['Net Growth Rate']
    ))
)

print('Net business growth rate added successfully!')

# Round for readability
wvsos_df['Net Growth Rate'] = wvsos_df['Net Growth Rate'].round(2)

print('Net business growth rate rounded successfully!')

# Data check
print('Data check:')
print('Data shape:', wvsos_df.shape)
wvsos_df.head()

Net business growth rate added successfully!
Net business growth rate rounded successfully!
Data check:
Data shape: (237549, 12)

,Organization Name,Org Type,Filing Year,Termination Year,Industry,Yearly Registrations,Yearly Closures,Net Business Change,Registration Share,HHI Business Formation,Net Growth Share,Net Growth Rate
773,"AMERICAN COLLEGE OF COUNSELORS, INC.",C | Corporation,2019,<NA>,Health Care and Social Assistance,418,0,418,0.03,1154,0.01,9.15
1128,"ANVIL OIL & GAS CO., INC.",C | Corporation,2013,2015,Unmapped,3289,4596,-1307,0.29,1381,0.05,-84.94
1516,"UNITED ANESTHESIA, INC.",C | Corporation,2015,<NA>,Health Care and Social Assistance,370,0,370,0.03,1245,0.01,-12.32
1761,"B & B LOANS OF LOGAN, INC.",C | Corporation,2018,<NA>,"Trade, Transportation, and Utilities",1595,0,1595,0.12,1291,0.14,1.29
1777,"ROTHCO FORD, INC.",C | Corporation,2017,2018,Real Estate and Rental and Leasing,1316,291,1025,0.11,1196,0.16,-16.22

In [351]:
# Reset index
wvsos_clean = wvsos_df.reset_index(drop=True)

print('Index reset successfully!')

# Save cleaned data
wvsos_clean.to_csv('../../../workspace/nf-insights-project/data_clean/wvsos_business_registrations_clean.csv', index=False)

print('CSV saved successfully!')

Index reset successfully!
CSV saved successfully!